# Upright Thoth meanings — Major Arcana (Book of Thoth titles + Jungian subs).
UP_MAJOR = {
  "maj00": [  # The Fool — Air, pure spirit, zero
    ("embodying", "zero", ["the point before all points", "spirit not yet condensed", "pure potential, no form yet", "the green man dancing", "everything held in nothing"]),
    ("leaping", "into being", ["stepping off the known edge", "trusting the air to hold", "movement before meaning", "the divine fool's abandon", "saying yes to incarnation"]),
    ("", "innocence", ["the puer, eternally young", "ego before it divides the world", "wholeness not yet split", "wonder uncalculated", "the unfallen self"]),
    ("carrying", "all elements", ["the wallet of unspent gifts", "every suit folded in one", "tiger and crocodile both", "spirit ungoverned by sense"]),
  ],
  "maj01": [  # The Magus — Mercury, the Word, will & skill
    ("wielding", "the word", ["speaking reality into form", "will made articulate", "the message becomes the medium", "thought tipped with intent", "naming the thing to call it"]),
    ("juggling", "forces", ["all four tools in play", "keeping every element aloft", "directing energy through skill", "the magician's swift hands"]),
    ("", "mercury", ["quicksilver intelligence", "the trickster who reveals", "logos shaping matter", "wit as a working tool"]),
    ("channeling", "will", ["becoming conduit, not source", "aligning desire with act", "the true will moving through you"]),
  ],
  "maj02": [  # The Priestess — Moon, the veil, intuition
    ("keeping", "the veil", ["guarding what can't be spoken", "the threshold between worlds", "mystery that resists capture", "silence as a kind of speech"]),
    ("", "intuition", ["knowing without evidence", "the lunar tide in you", "trusting the inner water", "the anima's quiet counsel"]),
    ("reflecting", "light", ["the moon borrowing the sun", "receiving before acting", "stillness that mirrors truth", "becoming a clear pool"]),
    ("holding", "the secret", ["wisdom not yet ready to speak", "the unconscious holding its cards", "potential coiled in the dark"]),
  ],
  "maj03": [  # The Empress — Venus, love, fertility
    ("", "abundance", ["fertility overflowing", "nature giving freely", "beauty as a force of growth", "the green world ripening"]),
    ("loving", "openly", ["venusian warmth", "desire that creates", "tenderness with power", "eros as life force"]),
    ("mothering", "creation", ["the great mother's embrace", "nourishing what you've made", "holding the growing thing", "love that builds bodies"]),
    ("", "beauty", ["harmony made visible", "pleasure without apology", "the senses honored", "grace in the material"]),
  ],
  "maj04": [  # The Emperor — Aries, authority, structure
    ("", "authority", ["the will that organizes", "sovereignty earned, not seized", "standing as the fixed point", "command that protects"]),
    ("building", "structure", ["giving chaos a frame", "laws that let things grow", "the architecture of order", "boundaries as kindness"]),
    ("fathering", "the realm", ["the senex's steady hand", "providing the container", "leadership as responsibility"]),
    ("", "fire", ["aries energy directed", "drive shaped into rule", "ambition with a throne"]),
  ],
  "maj05": [  # The Hierophant — Taurus, teaching, tradition
    ("", "teaching", ["the bridge to the sacred", "wisdom handed down", "the outer form of inner truth", "ritual that opens a door"]),
    ("keeping", "tradition", ["the lineage carried forward", "the vessel of the mysteries", "belonging through shared rite"]),
    ("blessing", "the seeker", ["the wise old man's counsel", "initiation offered", "sanction from above"]),
    ("", "the word", ["the new aeon spoken", "doctrine made living", "meaning behind the form"]),
  ],
  "maj06": [  # The Lovers — Gemini, the alchemical marriage
    ("", "union", ["opposites married", "the alchemical wedding", "two becoming a third thing", "the coniunctio achieved"]),
    ("choosing", "rightly", ["the oracle over the impulse", "discrimination then union", "the vow made conscious", "love as a decision"]),
    ("joining", "opposites", ["king and queen wedded", "sun and moon reconciled", "the syzygy within you", "analysis then synthesis"]),
    ("", "the child", ["what the union creates", "innocence reborn from two", "the third that heals the split"]),
  ],
  "maj07": [  # The Chariot — Cancer, the Grail, triumph by balance
    ("", "triumph", ["victory by holding the reins", "forces yoked, not fought", "momentum under control", "the still center moving fast"]),
    ("carrying", "the grail", ["the vessel held steady", "bearing something sacred", "the cup amid the speed"]),
    ("directing", "opposites", ["black and white sphinxes pull", "ego steering its drives", "willpower as armor"]),
    ("", "control", ["stillness inside motion", "mastery that needn't strain", "command of the inner team"]),
  ],
  "maj08": [  # Adjustment (Thoth Justice) — Libra, balance, truth
    ("", "balance", ["the scales finding true", "every act answered exactly", "equilibrium as the law", "the dancer poised on a point"]),
    ("weighing", "truth", ["the feather against the heart", "seeing without distortion", "maat's impartial gaze", "fact severed from wish"]),
    ("adjusting", "the self", ["the transcendent function at work", "correcting the inner imbalance", "tuning toward fairness"]),
    ("", "karma", ["cause and effect made visible", "the debt settled precisely", "consequence without cruelty"]),
  ],
  "maj09": [  # The Hermit — Virgo, solitude, the inner light
    ("", "solitude", ["withdrawing to find the light", "the cave as a workshop", "quiet that ripens insight", "being alone, not lonely"]),
    ("carrying", "the lamp", ["the inner light shown outward", "wisdom lighting one step", "the secret flame guarded"]),
    ("", "the seed", ["growth hidden in the dark", "virgo's fertile patience", "what germinates unseen"]),
    ("seeking", "the self", ["the wise old man within", "introversion as a path", "meeting yourself in the still"]),
  ],
  "maj10": [  # Fortune (Wheel) — Jupiter, cycles, change
    ("", "the turn", ["the wheel always moving", "change as the only constant", "fortune favoring motion", "what's down will rise"]),
    ("riding", "cycles", ["jupiter's expansion", "the gunas spinning", "accepting the rhythm", "luck meeting readiness"]),
    ("", "synchronicity", ["meaningful coincidence", "fate winking through chance", "the pattern beneath events"]),
    ("trusting", "flux", ["letting the wheel carry you", "change without grasping", "the long view of fate"]),
  ],
  "maj11": [  # Lust (Thoth Strength) — Leo, joy of strength, the beast ridden
    ("", "lust for life", ["strength felt as joy", "appetite for existence", "riding the beast, not caging it", "courage that laughs"]),
    ("", "ecstasy", ["passion as a sacred force", "the holy whore's abandon", "desire fully owned", "union with the wild"]),
    ("riding", "the beast", ["the instincts ridden well", "libido affirmed, not feared", "the shadow made an ally"]),
    ("", "vitality", ["the lion's solar heat", "power that delights", "raw life saying yes"]),
  ],
  "maj12": [  # The Hanged Man — Water, surrender, reversal
    ("", "surrender", ["letting go of the struggle", "sacrifice made willingly", "release as a doorway", "hanging between worlds"]),
    ("reversing", "the view", ["the world seen upside down", "new sight from suspension", "what inversion reveals", "perspective bought by pause"]),
    ("", "the sacrifice", ["the dying god's gift", "ego offered up", "losing to gain", "drowning the old self"]),
    ("waiting", "in water", ["stillness before rebirth", "suspended, not stuck", "trusting the long pause"]),
  ],
  "maj13": [  # Death — Scorpio, transformation, putrefaction
    ("", "transformation", ["the old form dissolving", "death as a passage, not an end", "clearing for the new", "scorpio's deep change"]),
    ("harvesting", "the dead", ["the scythe cutting clean", "what's finished, finishing", "necessary endings", "reaping the spent"]),
    ("", "putrefaction", ["the nigredo, blackening", "rot that feeds the next life", "decay as alchemy"]),
    ("releasing", "the form", ["shedding the outworn skin", "letting the husk fall", "change you can't reverse"]),
  ],
  "maj14": [  # Art (Thoth Temperance) — Sagittarius, the great work
    ("", "the great work", ["opposites fused in the cauldron", "fire and water made one", "alchemy of the self", "gold from contraries"]),
    ("tempering", "extremes", ["blending what fought", "the middle way forged", "moderation as a craft", "two streams, one vessel"]),
    ("", "synthesis", ["the transcendent function", "integration into wholeness", "the rainbow over the brew"]),
    ("transmuting", "the base", ["lead toward gold", "raw matter refined", "the slow patient cooking"]),
  ],
  "maj15": [  # The Devil — Capricorn, matter, mirth, bondage
    ("", "matter", ["the goat dancing in flesh", "creative force in the dense", "desire rooted in earth", "the body's blunt joy"]),
    ("", "bondage", ["chains loose enough to drop", "what you cling to clings back", "the shadow you won't own", "appetite running the house"]),
    ("laughing", "in the dark", ["the god of mirth", "ecstasy without apology", "capricorn's earthy humor"]),
    ("facing", "the shadow", ["meeting the disowned", "the devil as your own mask", "integrating the instinct"]),
  ],
  "maj16": [  # The Tower — Mars, lightning, sudden collapse
    ("", "the lightning", ["the false struck down", "sudden necessary collapse", "mars breaking the prison", "truth that arrives as shock"]),
    ("burning", "the tower", ["the structure that must fall", "ego's fortress shattered", "clearing by fire"]),
    ("", "revelation", ["the eye of shiva opens", "what the ruin uncovers", "liberation through breakdown"]),
    ("falling", "free", ["thrown from the false safety", "the persona cracking off", "release in the rubble"]),
  ],
  "maj17": [  # The Star — Aquarius, hope, Nuit pouring
    ("", "hope", ["light after the tower's fall", "the star that steadies you", "quiet faith renewed", "calm pouring in"]),
    ("pouring", "the water", ["nuit's endless giving", "feeding earth and stream both", "generosity from the source"]),
    ("", "guidance", ["the star to steer by", "the anima leading on", "the transpersonal touch"]),
    ("", "renewal", ["washed clean and open", "meditation's clear pool", "trust restored gently"]),
  ],
  "maj18": [  # The Moon — Pisces, illusion, the dark path
    ("", "illusion", ["light that deceives", "the path through the fog", "what the moon distorts", "fear dressed as fact"]),
    ("crossing", "the dark", ["the gateway between towers", "walking through the test", "the descent you must make"]),
    ("", "the unconscious", ["the deep waters stirring", "old fears surfacing", "projection mistaken for world"]),
    ("trusting", "the path", ["moving though you can't see", "the dog and wolf both howling", "faith in the unseen road"]),
  ],
  "maj19": [  # The Sun — joy, clarity, the regenerated self
    ("", "joy", ["the sun's unguarded light", "clarity that warms", "life affirmed simply", "the dancing children"]),
    ("", "clarity", ["everything seen plainly", "no shadow left to hide", "consciousness at noon"]),
    ("shining", "freely", ["the regenerated self", "light given without fear", "the lord of life awake"]),
    ("", "wholeness", ["the self made radiant", "integration shining out", "the green earth blessed"]),
  ],
  "maj20": [  # The Aeon (Thoth Judgement) — Fire/Spirit, Horus, awakening
    ("", "the new aeon", ["horus crowned and conquering", "the old law ending", "awakening to a new age", "the child of the future"]),
    ("answering", "the call", ["rising to the summons", "the deep voice heard", "stepping into rebirth"]),
    ("", "awakening", ["consciousness reborn", "the self called higher", "the stele revealing"]),
    ("judging", "nothing", ["beyond reward and blame", "the new law of freedom", "accounting transcended"]),
  ],
  "maj21": [  # The Universe (Thoth World) — Saturn/Earth, completion
    ("", "completion", ["the great work fulfilled", "the circle closed", "all parts in their place", "the dance finished and begun"]),
    ("dancing", "the whole", ["matter celebrating itself", "the maiden in the wreath", "saturn's structure made joy"]),
    ("", "the mandala", ["the self made whole", "individuation complete", "the four held in one"]),
    ("", "synthesis", ["every element woven in", "the body of the universe", "the end that is a return"]),
  ],
}
