// Tarot de Marseille meanings (reversed). Four angles —
// Weakened / Inverted / Negative / Delayed. For the minors the
// number (or court rank) supplies the shape of the failure and
// the suit supplies what is failing.
// Generated by marseille/_gen_meanings.py — edit the content
// modules there, not this file.
const CARD_ACTIONS_REVERSED_MARSEILLE = {
  "maj00": [
    {"lead": "Weakened", "key": "wandering", "subs": ["the road losing its pull", "freedom that feels like drift", "lightness thinning into vacancy", "movement without appetite"]},
    {"lead": "Inverted", "key": "freedom", "subs": ["rootlessness dressed as liberty", "leaving before anything can hold", "the escape that repeats itself", "no place refused, none entered"]},
    {"lead": "Negative", "key": "evasion", "subs": ["using the road to dodge the work", "irresponsibility called openness", "the bundle never unpacked", "never staying to be known"]},
    {"lead": "Delayed", "key": "departure", "subs": ["the setting-out still ahead", "the dog still nipping unheeded", "readiness not yet turned to leaving", "the road waiting to be taken"]}
  ],
  "maj01": [
    {"lead": "Weakened", "key": "skill", "subs": ["the hands less sure than they look", "craft that will not quite land", "tools laid out but not used", "the opening act faltering"]},
    {"lead": "Inverted", "key": "beginning", "subs": ["the shop open with nothing to sell", "gesture standing in for work", "starting again to avoid finishing", "showmanship over substance"]},
    {"lead": "Negative", "key": "trickery", "subs": ["sleight of hand used to deceive", "talent spent on the con", "the table set to distract", "cleverness without conscience"]},
    {"lead": "Delayed", "key": "the work", "subs": ["the craft still being learned", "tools present, mastery pending", "the first move not yet made", "readiness arriving slowly"]}
  ],
  "maj02": [
    {"lead": "Weakened", "key": "the watch", "subs": ["the hundred eyes drooping shut", "vigilance thinning to habit", "the vow kept in name only", "majesty losing its bearing"]},
    {"lead": "Inverted", "key": "vigilance", "subs": ["watching instead of living", "the guard kept on the wrong door", "suspicion dressed as care", "seeing everything, trusting nothing"]},
    {"lead": "Negative", "key": "jealousy", "subs": ["the watch turned to possession", "punishing what cannot be held", "the peacock's eyes as evidence", "love enforced like a law"]},
    {"lead": "Delayed", "key": "the vow", "subs": ["the promise not yet kept", "the threshold not yet crossed", "recognition still to come", "her moment waiting on the sky"]}
  ],
  "maj03": [
    {"lead": "Weakened", "key": "increase", "subs": ["growth that will not quite take", "abundance short of arriving", "fertility running thin", "the shield heavy on the arm"]},
    {"lead": "Inverted", "key": "nurture", "subs": ["tending that smothers", "care given to be needed", "protection that prevents growing", "the shelter become an enclosure"]},
    {"lead": "Negative", "key": "possession", "subs": ["nurture as a claim of ownership", "creating in order to control", "generosity with strings", "abundance used as leverage"]},
    {"lead": "Delayed", "key": "flourishing", "subs": ["the season not yet turned", "what is planted still underground", "fruit forming out of sight", "increase on its own timetable"]}
  ],
  "maj04": [
    {"lead": "Weakened", "key": "structure", "subs": ["the order beginning to give", "authority that no longer convinces", "solidity with a hairline crack", "the seat less firm than it looks"]},
    {"lead": "Inverted", "key": "stability", "subs": ["rigidity passed off as strength", "immovability as the only answer", "order preserved past its use", "structure serving only itself"]},
    {"lead": "Negative", "key": "domination", "subs": ["rule enforced because it can be", "control mistaken for care", "power that permits no question", "the father as a closed door"]},
    {"lead": "Delayed", "key": "order", "subs": ["the ground still settling", "authority not yet earned", "structure being built slowly", "the seat waiting to be taken"]}
  ],
  "maj05": [
    {"lead": "Weakened", "key": "command", "subs": ["thunder held without the charge", "authority that must repeat itself", "the eagle flying lower", "law announced, not felt"]},
    {"lead": "Inverted", "key": "authority", "subs": ["rule from too far above to see", "the sky talking over the ground", "power that answers no questions", "grandeur standing in for judgement"]},
    {"lead": "Negative", "key": "the bolt", "subs": ["the strike before the hearing", "punishment as first resort", "favour sold, wrath free", "the father who only says no"]},
    {"lead": "Delayed", "key": "the answer", "subs": ["the petition still ascending", "the sky quiet for now", "judgement gathering like weather", "the yes not yet spoken"]}
  ],
  "maj06": [
    {"lead": "Weakened", "key": "choosing", "subs": ["the decision losing its edge", "both paths dimming at once", "the arrow loosed but unaimed", "commitment that will not set"]},
    {"lead": "Inverted", "key": "love", "subs": ["choice deferred to keep both", "attachment mistaken for decision", "wanting the fork, not the road", "loving in order not to choose"]},
    {"lead": "Negative", "key": "indecision", "subs": ["refusing to elect anything", "keeping options as a strategy", "the cost passed to other people", "paralysis dressed as openness"]},
    {"lead": "Delayed", "key": "the decision", "subs": ["the crossing still ahead", "the arrow still in flight", "clarity about to arrive", "the choice ripening"]}
  ],
  "maj07": [
    {"lead": "Weakened", "key": "momentum", "subs": ["the horses pulling unevenly", "drive that will not quite gather", "the car moving without aim", "advance losing its force"]},
    {"lead": "Inverted", "key": "victory", "subs": ["the vehicle mistaken for the journey", "conquest sought for the look of it", "arriving nowhere, splendidly", "motion as its own excuse"]},
    {"lead": "Negative", "key": "conquest", "subs": ["driving over rather than through", "will that flattens what it meets", "triumph that costs the country", "steering by ego alone"]},
    {"lead": "Delayed", "key": "arrival", "subs": ["the campaign still under way", "the destination not yet in view", "progress real but unfinished", "the road longer than expected"]}
  ],
  "maj08": [
    {"lead": "Weakened", "key": "balance", "subs": ["the scales trembling, not settling", "judgement that will not resolve", "the sword lowered a little", "measure losing its nerve"]},
    {"lead": "Inverted", "key": "justice", "subs": ["the rule applied to the wrong case", "fairness used as a weapon", "the letter honoured, the spirit lost", "weighing rigged before it starts"]},
    {"lead": "Negative", "key": "judgement", "subs": ["condemnation enjoying itself", "severity mistaken for principle", "the blade before the balance", "verdict without hearing"]},
    {"lead": "Delayed", "key": "the verdict", "subs": ["the weighing still in progress", "the case not yet complete", "fairness arriving slowly", "the sword still held level"]}
  ],
  "maj09": [
    {"lead": "Weakened", "key": "the light", "subs": ["the lantern guttering low", "prudence thinning into doubt", "the next step barely lit", "the staff taking too much weight"]},
    {"lead": "Inverted", "key": "solitude", "subs": ["withdrawal that became a habit", "the lamp turned inward only", "distance kept past its purpose", "quiet hardened into refusal"]},
    {"lead": "Negative", "key": "isolation", "subs": ["solitude used to avoid people", "wisdom hoarded, never offered", "the cloak hiding the light entirely", "alone as an identity"]},
    {"lead": "Delayed", "key": "the answer", "subs": ["the search still under way", "the light not yet reaching it", "understanding a few steps off", "patience still being asked"]}
  ],
  "maj10": [
    {"lead": "Weakened", "key": "the turn", "subs": ["the wheel barely moving", "luck that will not commit", "change stalled mid-rotation", "momentum leaking away"]},
    {"lead": "Inverted", "key": "fortune", "subs": ["chance read as personal desert", "credit taken for the upswing", "the fall treated as injustice", "the wheel mistaken for a throne"]},
    {"lead": "Negative", "key": "fatalism", "subs": ["surrendering agency to the turn", "using luck to excuse everything", "waiting where you could act", "the wheel as an alibi"]},
    {"lead": "Delayed", "key": "the change", "subs": ["the turn beginning but not landed", "the cycle still coming round", "timing not yet yours", "what rises still rising"]}
  ],
  "maj11": [
    {"lead": "Weakened", "key": "strength", "subs": ["the hands unsure on the jaws", "calm that costs visible effort", "gentleness thinning to nerve", "the grip loosening"]},
    {"lead": "Inverted", "key": "gentleness", "subs": ["softness used to avoid the beast", "patience that never acts", "the mouth held shut, not opened", "control mistaken for peace"]},
    {"lead": "Negative", "key": "force", "subs": ["mastery slipping into domination", "the animal beaten, not held", "appetite ruling the hands", "strength that needs to prove itself"]},
    {"lead": "Delayed", "key": "mastery", "subs": ["the beast not yet befriended", "steadiness still being learned", "courage arriving in stages", "the quiet hand still forming"]}
  ],
  "maj12": [
    {"lead": "Weakened", "key": "suspension", "subs": ["the pause losing its meaning", "waiting that has gone numb", "stillness without insight", "hanging with nothing gained"]},
    {"lead": "Inverted", "key": "surrender", "subs": ["sacrifice performed for witnesses", "the pose held to avoid deciding", "martyrdom mistaken for patience", "letting go of the wrong thing"]},
    {"lead": "Negative", "key": "stagnation", "subs": ["suspension chosen as a hiding place", "inversion that refuses to right", "waiting used to avoid the cost", "the coins spilled and unmissed"]},
    {"lead": "Delayed", "key": "the release", "subs": ["the rope not yet cut", "the new view still forming", "the pause not finished with you", "descent still to come"]}
  ],
  "maj13": [
    {"lead": "Weakened", "key": "the ending", "subs": ["the cut that will not complete", "clearance stalled halfway", "the blade slowed in the soil", "an end that keeps not ending"]},
    {"lead": "Inverted", "key": "change", "subs": ["holding what is already gone", "tending a field long since cut", "refusing the harvest", "the nameless thing given a name"]},
    {"lead": "Negative", "key": "clinging", "subs": ["preserving a corpse of a situation", "fear of ending running the choice", "the scythe resisted at any cost", "life spent guarding an ending"]},
    {"lead": "Delayed", "key": "the clearing", "subs": ["the ground not yet turned", "what must go still going", "the field mid-harvest", "renewal waiting on the cut"]}
  ],
  "maj14": [
    {"lead": "Weakened", "key": "the flow", "subs": ["the pour thinning to a trickle", "proportion slightly off", "the exchange losing its rhythm", "balance kept with effort"]},
    {"lead": "Inverted", "key": "moderation", "subs": ["temperance as refusal to feel", "mixing to avoid choosing", "the middle taken from fear", "blandness called balance"]},
    {"lead": "Negative", "key": "excess", "subs": ["the vessels emptied carelessly", "proportion abandoned entirely", "combining what should stay apart", "the cure taken past its dose"]},
    {"lead": "Delayed", "key": "the blend", "subs": ["the mixture still finding itself", "healing on a slow schedule", "the right measure not yet found", "the pouring still under way"]}
  ],
  "maj15": [
    {"lead": "Weakened", "key": "the grip", "subs": ["the compulsion losing its hold", "appetite quieter than it was", "the tethers gone slack", "the torch burning lower"]},
    {"lead": "Inverted", "key": "bondage", "subs": ["the chain admired as jewellery", "captivity called preference", "the pedestal defended by the bound", "wanting the bond to remain"]},
    {"lead": "Negative", "key": "compulsion", "subs": ["appetite fully in the throne", "using others as instruments", "the ropes tightened deliberately", "power built on someone's need"]},
    {"lead": "Delayed", "key": "release", "subs": ["the rope loosening slowly", "the grip not yet broken", "freedom recognised, not taken", "the step off the pedestal pending"]}
  ],
  "maj16": [
    {"lead": "Weakened", "key": "the strike", "subs": ["the shock partly absorbed", "the crack held, for now", "collapse arrested midway", "the tower swaying, standing"]},
    {"lead": "Inverted", "key": "collapse", "subs": ["dismantling the tower yourself", "courting the strike to feel alive", "ruin sought as a shortcut", "breaking to avoid rebuilding"]},
    {"lead": "Negative", "key": "destruction", "subs": ["tearing down what could be repaired", "the fall taken out on others", "crisis manufactured, then blamed", "wreckage kept as an excuse"]},
    {"lead": "Delayed", "key": "the fall", "subs": ["the lightning already on its way", "the crack widening unseen", "what must break not yet broken", "the shelter on borrowed time"]}
  ],
  "maj17": [
    {"lead": "Weakened", "key": "hope", "subs": ["the star faint behind cloud", "the jugs pouring slowly", "encouragement barely reaching", "replenishment slowed to a drip"]},
    {"lead": "Inverted", "key": "renewal", "subs": ["hope used to postpone action", "waiting on the star to do it", "optimism as an anaesthetic", "the stream admired, not entered"]},
    {"lead": "Negative", "key": "despair", "subs": ["refusing the water outright", "the sky read as empty", "cynicism dressed as realism", "the jugs set down for good"]},
    {"lead": "Delayed", "key": "restoration", "subs": ["the pool refilling slowly", "hope arriving out of season", "the star still coming clear", "the healing not yet felt"]}
  ],
  "maj18": [
    {"lead": "Weakened", "key": "the light", "subs": ["the moon behind thickening cloud", "instinct that will not settle", "the path fading at the edges", "guidance intermittent"]},
    {"lead": "Inverted", "key": "illusion", "subs": ["the dream taken as instruction", "reading omens into everything", "feeling promoted to fact", "the tide mistaken for direction"]},
    {"lead": "Negative", "key": "deception", "subs": ["preferring the fog to the fact", "using the night to hide in", "self-deceit maintained on purpose", "what surfaces pushed back down"]},
    {"lead": "Delayed", "key": "clarity", "subs": ["the crayfish still climbing", "the night not finished yet", "dawn a long way off but coming", "the path revealing itself slowly"]}
  ],
  "maj19": [
    {"lead": "Weakened", "key": "the day", "subs": ["light present but not warming", "gladness that will not quite come", "the wall throwing a small shadow", "brightness held at a distance"]},
    {"lead": "Inverted", "key": "clarity", "subs": ["cheerfulness worn as armour", "simplicity performed for company", "the plain good made a duty", "shining to be seen shining"]},
    {"lead": "Negative", "key": "glare", "subs": ["exposure with nowhere to stand", "optimism that flattens the real", "warmth demanded of everyone", "light that refuses any shade"]},
    {"lead": "Delayed", "key": "the warmth", "subs": ["the sun still climbing", "the good day not yet here", "clarity arriving after the night", "the drops still falling"]}
  ],
  "maj20": [
    {"lead": "Weakened", "key": "the call", "subs": ["the trumpet heard faintly", "the summons not quite landing", "rising begun and abandoned", "the lid pushed but not moved"]},
    {"lead": "Inverted", "key": "reckoning", "subs": ["answering a charge no one made", "self-judgement mistaken for the call", "rising for the wrong summons", "the account rendered to yourself"]},
    {"lead": "Negative", "key": "condemnation", "subs": ["the call used to accuse", "judgement without the restoration", "the past held over the living", "waking others only to blame"]},
    {"lead": "Delayed", "key": "the waking", "subs": ["the note still travelling", "the tomb still shut", "the reckoning ahead, not now", "return being prepared"]}
  ],
  "maj21": [
    {"lead": "Weakened", "key": "completion", "subs": ["the wreath not quite closed", "wholeness missing one quarter", "the dance slowing near the end", "arrival that will not settle"]},
    {"lead": "Inverted", "key": "wholeness", "subs": ["the garland worn as a boundary", "completion used to stop moving", "the world held rather than entered", "finishing to avoid beginning"]},
    {"lead": "Negative", "key": "closure", "subs": ["sealing the circle against entry", "wholeness that excludes", "the frame mistaken for the world", "completion defended, not lived"]},
    {"lead": "Delayed", "key": "arrival", "subs": ["the round still being danced", "the fourth corner not yet present", "the wreath still being woven", "completion on its long approach"]}
  ],
  "wands01": [
    {"lead": "Weakened", "key": "the seed", "subs": ["potential that will not germinate", "the gift declined", "a beginning that keeps not starting", "the offer left on the table"]},
    {"lead": "Inverted", "key": "beginning", "subs": ["potential hoarded as identity", "the start endlessly rehearsed", "possibility preferred to actuality", "keeping the gift unopened"]},
    {"lead": "Negative", "key": "the fire", "subs": ["squandering what was given freely", "the seed spent on nothing", "beginning in order never to finish", "wasting a genuine opening"]},
    {"lead": "Delayed", "key": "germination", "subs": ["the seed still under the soil", "germination on its own schedule", "the beginning not yet due", "potential waiting for its season"]}
  ],
  "wands02": [
    {"lead": "Weakened", "key": "the pair", "subs": ["the bond thinning", "exchange that has gone one-way", "relation losing its charge", "two drifting out of contact"]},
    {"lead": "Inverted", "key": "union", "subs": ["union sought to avoid being one", "pairing as a hiding place", "the other used as a mirror", "relation that erases both"]},
    {"lead": "Negative", "key": "the fire", "subs": ["the bond kept for leverage", "dependency dressed as devotion", "tying another to your lack", "partnership as quiet control"]},
    {"lead": "Delayed", "key": "the meeting", "subs": ["the meeting not yet made", "the pair still forming", "connection arriving late", "the second half still on its way"]}
  ],
  "wands03": [
    {"lead": "Weakened", "key": "the issue", "subs": ["growth that stalls early", "the result thinner than hoped", "expression losing its nerve", "the third not quite arriving"]},
    {"lead": "Inverted", "key": "growth", "subs": ["output produced for the look of it", "growth pursued past its use", "expression as performance", "fruit forced before ripening"]},
    {"lead": "Negative", "key": "the fire", "subs": ["creating in order to be admired", "the work exploiting its makers", "growth that consumes its ground", "fertility turned to excess"]},
    {"lead": "Delayed", "key": "the result", "subs": ["the result still forming", "expression finding its shape", "growth on a slow schedule", "the third not yet born"]}
  ],
  "wands04": [
    {"lead": "Weakened", "key": "the square", "subs": ["the structure loosening", "stability with a crack in it", "the enclosure less firm than it looks", "order beginning to slip"]},
    {"lead": "Inverted", "key": "stability", "subs": ["walls kept after the need has passed", "stability defended as an identity", "the pause become permanent", "structure serving only itself"]},
    {"lead": "Negative", "key": "the fire", "subs": ["the enclosure used to shut others out", "security bought with rigidity", "hoarding disguised as prudence", "order enforced without reason"]},
    {"lead": "Delayed", "key": "consolidation", "subs": ["the structure still being built", "stability not yet reached", "the square not yet closed", "consolidation still under way"]}
  ],
  "wands05": [
    {"lead": "Weakened", "key": "the break", "subs": ["disruption that will not resolve", "the disturbance dragging on", "instability become the norm", "the pivot stuck mid-turn"]},
    {"lead": "Inverted", "key": "disruption", "subs": ["conflict maintained on purpose", "crisis preferred to settlement", "the break made into a home", "disruption as an identity"]},
    {"lead": "Negative", "key": "the fire", "subs": ["breaking things to feel the movement", "the wound kept deliberately open", "crisis manufactured for advantage", "harm passed on down the line"]},
    {"lead": "Delayed", "key": "resolution", "subs": ["the disruption still working through", "the break not yet healed", "movement that has further to go", "resolution some way off"]}
  ],
  "wands06": [
    {"lead": "Weakened", "key": "the balance", "subs": ["harmony that will not quite hold", "exchange slightly off true", "the middle wobbling", "proportion drifting"]},
    {"lead": "Inverted", "key": "harmony", "subs": ["balance kept by suppressing one side", "harmony that forbids disagreement", "the peace of not speaking", "evenness enforced, not found"]},
    {"lead": "Negative", "key": "the fire", "subs": ["fairness used to avoid generosity", "the exchange rigged and called even", "harmony demanded of others only", "balance as a way to withhold"]},
    {"lead": "Delayed", "key": "the exchange", "subs": ["the balance still being found", "the exchange not yet even", "harmony arriving gradually", "the middle still being located"]}
  ],
  "wands07": [
    {"lead": "Weakened", "key": "the trial", "subs": ["effort losing its edge", "resistance wearing you down", "the test dragging past its point", "strain without progress"]},
    {"lead": "Inverted", "key": "the struggle", "subs": ["difficulty sought to prove something", "the trial extended on purpose", "struggle as a badge", "hardship mistaken for merit"]},
    {"lead": "Negative", "key": "the fire", "subs": ["making it hard for everyone else", "the fight picked for its own sake", "effort that damages the effort", "grinding past all usefulness"]},
    {"lead": "Delayed", "key": "the outcome", "subs": ["the trial not yet finished", "the test still being sat", "resolution the far side of effort", "the strain still to be borne"]}
  ],
  "wands08": [
    {"lead": "Weakened", "key": "the order", "subs": ["the arrangement slipping", "structure under more load than it takes", "pattern beginning to fray", "organisation losing its grip"]},
    {"lead": "Inverted", "key": "structure", "subs": ["order kept past its usefulness", "structure that has forgotten its purpose", "arrangement as a form of control", "the system serving itself"]},
    {"lead": "Negative", "key": "the fire", "subs": ["order imposed regardless of cost", "efficiency above every other thing", "the pattern enforced on people", "structure used to exclude"]},
    {"lead": "Delayed", "key": "the pattern", "subs": ["the order still being assembled", "structure not yet holding", "arrangement still being tested", "the pattern still emerging"]}
  ],
  "wands09": [
    {"lead": "Weakened", "key": "the fullness", "subs": ["the height not quite reached", "sufficiency that does not satisfy", "fullness with something missing", "the summit thinning out"]},
    {"lead": "Inverted", "key": "sufficiency", "subs": ["completeness defended in solitude", "self-sufficiency as a wall", "fullness that refuses company", "having, and hiding it"]},
    {"lead": "Negative", "key": "the fire", "subs": ["abundance used to keep others out", "solitude at the top made a virtue", "hoarding the view", "sufficiency that excludes"]},
    {"lead": "Delayed", "key": "the summit", "subs": ["the fullness still filling", "the height still being climbed", "sufficiency near but not here", "the last stretch remaining"]}
  ],
  "wands10": [
    {"lead": "Weakened", "key": "the overflow", "subs": ["completion tipping into too much", "the container failing", "surplus becoming burden", "the end that will not end"]},
    {"lead": "Inverted", "key": "completion", "subs": ["completion refused so it can continue", "the surplus kept from circulating", "ending avoided by adding more", "excess mistaken for success"]},
    {"lead": "Negative", "key": "the fire", "subs": ["overflow dumped onto other people", "hoarding at the point of plenty", "the weight passed down the line", "surplus that crushes its holder"]},
    {"lead": "Delayed", "key": "the return", "subs": ["the cycle still closing", "the return to one still coming", "completion on its final approach", "the overflow not yet released"]}
  ],
  "wands11": [
    {"lead": "Weakened", "key": "the apprentice", "subs": ["eagerness without follow-through", "study that will not settle", "the message half-delivered", "keenness thinning quickly"]},
    {"lead": "Inverted", "key": "learning", "subs": ["beginning endlessly to avoid mastering", "the student role kept too long", "curiosity as a way of not committing", "learning performed, not done"]},
    {"lead": "Negative", "key": "the fire", "subs": ["the messenger who distorts the message", "immaturity used as an excuse", "talent squandered on distraction", "promise traded on indefinitely"]},
    {"lead": "Delayed", "key": "readiness", "subs": ["the apprenticeship still running", "skill still being gathered", "the message still on its way", "readiness not yet arrived"]}
  ],
  "wands12": [
    {"lead": "Weakened", "key": "the quest", "subs": ["momentum draining", "the ride losing its direction", "commitment that will not hold pace", "the journey stalling"]},
    {"lead": "Inverted", "key": "the ride", "subs": ["movement chosen to avoid arriving", "the quest as a way of leaving", "speed mistaken for progress", "riding past what you wanted"]},
    {"lead": "Negative", "key": "the fire", "subs": ["charging over other people", "recklessness with someone else's ground", "the journey that ruins what it crosses", "haste made into a virtue"]},
    {"lead": "Delayed", "key": "arrival", "subs": ["the ride still under way", "arrival further off than it looked", "the quest mid-course", "the destination still ahead"]}
  ],
  "wands13": [
    {"lead": "Weakened", "key": "the inward hold", "subs": ["mastery that is costing effort", "depth harder to reach than usual", "the inner grip loosening", "composure thinning"]},
    {"lead": "Inverted", "key": "depth", "subs": ["interiority used to stay unreachable", "depth as a way of withholding", "understanding kept private on principle", "the vessel that never pours"]},
    {"lead": "Negative", "key": "the fire", "subs": ["reading others in order to manage them", "empathy turned to advantage", "inwardness that swallows other people", "depth used to dominate quietly"]},
    {"lead": "Delayed", "key": "mastery", "subs": ["the mastery still forming", "depth still being earned", "the inward work unfinished", "understanding still gathering"]}
  ],
  "wands14": [
    {"lead": "Weakened", "key": "the rule", "subs": ["authority losing its weight", "command that no longer carries", "the office held loosely", "power thinning at the edges"]},
    {"lead": "Inverted", "key": "authority", "subs": ["rule maintained for its own sake", "authority that has stopped serving", "the office mistaken for the person", "governing to remain governor"]},
    {"lead": "Negative", "key": "the fire", "subs": ["power used because it is available", "the rule enforced without care", "authority that permits no successor", "command as appetite"]},
    {"lead": "Delayed", "key": "the office", "subs": ["the authority still being earned", "the office not yet fully held", "rule arriving with experience", "power still consolidating"]}
  ],
  "cups01": [
    {"lead": "Weakened", "key": "the seed", "subs": ["potential that will not germinate", "the gift declined", "a beginning that keeps not starting", "the offer left on the table"]},
    {"lead": "Inverted", "key": "beginning", "subs": ["potential hoarded as identity", "the start endlessly rehearsed", "possibility preferred to actuality", "keeping the gift unopened"]},
    {"lead": "Negative", "key": "the water", "subs": ["squandering what was given freely", "the seed spent on nothing", "beginning in order never to finish", "wasting a genuine opening"]},
    {"lead": "Delayed", "key": "germination", "subs": ["the seed still under the soil", "germination on its own schedule", "the beginning not yet due", "potential waiting for its season"]}
  ],
  "cups02": [
    {"lead": "Weakened", "key": "the pair", "subs": ["the bond thinning", "exchange that has gone one-way", "relation losing its charge", "two drifting out of contact"]},
    {"lead": "Inverted", "key": "union", "subs": ["union sought to avoid being one", "pairing as a hiding place", "the other used as a mirror", "relation that erases both"]},
    {"lead": "Negative", "key": "the water", "subs": ["the bond kept for leverage", "dependency dressed as devotion", "tying another to your lack", "partnership as quiet control"]},
    {"lead": "Delayed", "key": "the meeting", "subs": ["the meeting not yet made", "the pair still forming", "connection arriving late", "the second half still on its way"]}
  ],
  "cups03": [
    {"lead": "Weakened", "key": "the issue", "subs": ["growth that stalls early", "the result thinner than hoped", "expression losing its nerve", "the third not quite arriving"]},
    {"lead": "Inverted", "key": "growth", "subs": ["output produced for the look of it", "growth pursued past its use", "expression as performance", "fruit forced before ripening"]},
    {"lead": "Negative", "key": "the water", "subs": ["creating in order to be admired", "the work exploiting its makers", "growth that consumes its ground", "fertility turned to excess"]},
    {"lead": "Delayed", "key": "the result", "subs": ["the result still forming", "expression finding its shape", "growth on a slow schedule", "the third not yet born"]}
  ],
  "cups04": [
    {"lead": "Weakened", "key": "the square", "subs": ["the structure loosening", "stability with a crack in it", "the enclosure less firm than it looks", "order beginning to slip"]},
    {"lead": "Inverted", "key": "stability", "subs": ["walls kept after the need has passed", "stability defended as an identity", "the pause become permanent", "structure serving only itself"]},
    {"lead": "Negative", "key": "the water", "subs": ["the enclosure used to shut others out", "security bought with rigidity", "hoarding disguised as prudence", "order enforced without reason"]},
    {"lead": "Delayed", "key": "consolidation", "subs": ["the structure still being built", "stability not yet reached", "the square not yet closed", "consolidation still under way"]}
  ],
  "cups05": [
    {"lead": "Weakened", "key": "the break", "subs": ["disruption that will not resolve", "the disturbance dragging on", "instability become the norm", "the pivot stuck mid-turn"]},
    {"lead": "Inverted", "key": "disruption", "subs": ["conflict maintained on purpose", "crisis preferred to settlement", "the break made into a home", "disruption as an identity"]},
    {"lead": "Negative", "key": "the water", "subs": ["breaking things to feel the movement", "the wound kept deliberately open", "crisis manufactured for advantage", "harm passed on down the line"]},
    {"lead": "Delayed", "key": "resolution", "subs": ["the disruption still working through", "the break not yet healed", "movement that has further to go", "resolution some way off"]}
  ],
  "cups06": [
    {"lead": "Weakened", "key": "the balance", "subs": ["harmony that will not quite hold", "exchange slightly off true", "the middle wobbling", "proportion drifting"]},
    {"lead": "Inverted", "key": "harmony", "subs": ["balance kept by suppressing one side", "harmony that forbids disagreement", "the peace of not speaking", "evenness enforced, not found"]},
    {"lead": "Negative", "key": "the water", "subs": ["fairness used to avoid generosity", "the exchange rigged and called even", "harmony demanded of others only", "balance as a way to withhold"]},
    {"lead": "Delayed", "key": "the exchange", "subs": ["the balance still being found", "the exchange not yet even", "harmony arriving gradually", "the middle still being located"]}
  ],
  "cups07": [
    {"lead": "Weakened", "key": "the trial", "subs": ["effort losing its edge", "resistance wearing you down", "the test dragging past its point", "strain without progress"]},
    {"lead": "Inverted", "key": "the struggle", "subs": ["difficulty sought to prove something", "the trial extended on purpose", "struggle as a badge", "hardship mistaken for merit"]},
    {"lead": "Negative", "key": "the water", "subs": ["making it hard for everyone else", "the fight picked for its own sake", "effort that damages the effort", "grinding past all usefulness"]},
    {"lead": "Delayed", "key": "the outcome", "subs": ["the trial not yet finished", "the test still being sat", "resolution the far side of effort", "the strain still to be borne"]}
  ],
  "cups08": [
    {"lead": "Weakened", "key": "the order", "subs": ["the arrangement slipping", "structure under more load than it takes", "pattern beginning to fray", "organisation losing its grip"]},
    {"lead": "Inverted", "key": "structure", "subs": ["order kept past its usefulness", "structure that has forgotten its purpose", "arrangement as a form of control", "the system serving itself"]},
    {"lead": "Negative", "key": "the water", "subs": ["order imposed regardless of cost", "efficiency above every other thing", "the pattern enforced on people", "structure used to exclude"]},
    {"lead": "Delayed", "key": "the pattern", "subs": ["the order still being assembled", "structure not yet holding", "arrangement still being tested", "the pattern still emerging"]}
  ],
  "cups09": [
    {"lead": "Weakened", "key": "the fullness", "subs": ["the height not quite reached", "sufficiency that does not satisfy", "fullness with something missing", "the summit thinning out"]},
    {"lead": "Inverted", "key": "sufficiency", "subs": ["completeness defended in solitude", "self-sufficiency as a wall", "fullness that refuses company", "having, and hiding it"]},
    {"lead": "Negative", "key": "the water", "subs": ["abundance used to keep others out", "solitude at the top made a virtue", "hoarding the view", "sufficiency that excludes"]},
    {"lead": "Delayed", "key": "the summit", "subs": ["the fullness still filling", "the height still being climbed", "sufficiency near but not here", "the last stretch remaining"]}
  ],
  "cups10": [
    {"lead": "Weakened", "key": "the overflow", "subs": ["completion tipping into too much", "the container failing", "surplus becoming burden", "the end that will not end"]},
    {"lead": "Inverted", "key": "completion", "subs": ["completion refused so it can continue", "the surplus kept from circulating", "ending avoided by adding more", "excess mistaken for success"]},
    {"lead": "Negative", "key": "the water", "subs": ["overflow dumped onto other people", "hoarding at the point of plenty", "the weight passed down the line", "surplus that crushes its holder"]},
    {"lead": "Delayed", "key": "the return", "subs": ["the cycle still closing", "the return to one still coming", "completion on its final approach", "the overflow not yet released"]}
  ],
  "cups11": [
    {"lead": "Weakened", "key": "the apprentice", "subs": ["eagerness without follow-through", "study that will not settle", "the message half-delivered", "keenness thinning quickly"]},
    {"lead": "Inverted", "key": "learning", "subs": ["beginning endlessly to avoid mastering", "the student role kept too long", "curiosity as a way of not committing", "learning performed, not done"]},
    {"lead": "Negative", "key": "the water", "subs": ["the messenger who distorts the message", "immaturity used as an excuse", "talent squandered on distraction", "promise traded on indefinitely"]},
    {"lead": "Delayed", "key": "readiness", "subs": ["the apprenticeship still running", "skill still being gathered", "the message still on its way", "readiness not yet arrived"]}
  ],
  "cups12": [
    {"lead": "Weakened", "key": "the quest", "subs": ["momentum draining", "the ride losing its direction", "commitment that will not hold pace", "the journey stalling"]},
    {"lead": "Inverted", "key": "the ride", "subs": ["movement chosen to avoid arriving", "the quest as a way of leaving", "speed mistaken for progress", "riding past what you wanted"]},
    {"lead": "Negative", "key": "the water", "subs": ["charging over other people", "recklessness with someone else's ground", "the journey that ruins what it crosses", "haste made into a virtue"]},
    {"lead": "Delayed", "key": "arrival", "subs": ["the ride still under way", "arrival further off than it looked", "the quest mid-course", "the destination still ahead"]}
  ],
  "cups13": [
    {"lead": "Weakened", "key": "the inward hold", "subs": ["mastery that is costing effort", "depth harder to reach than usual", "the inner grip loosening", "composure thinning"]},
    {"lead": "Inverted", "key": "depth", "subs": ["interiority used to stay unreachable", "depth as a way of withholding", "understanding kept private on principle", "the vessel that never pours"]},
    {"lead": "Negative", "key": "the water", "subs": ["reading others in order to manage them", "empathy turned to advantage", "inwardness that swallows other people", "depth used to dominate quietly"]},
    {"lead": "Delayed", "key": "mastery", "subs": ["the mastery still forming", "depth still being earned", "the inward work unfinished", "understanding still gathering"]}
  ],
  "cups14": [
    {"lead": "Weakened", "key": "the rule", "subs": ["authority losing its weight", "command that no longer carries", "the office held loosely", "power thinning at the edges"]},
    {"lead": "Inverted", "key": "authority", "subs": ["rule maintained for its own sake", "authority that has stopped serving", "the office mistaken for the person", "governing to remain governor"]},
    {"lead": "Negative", "key": "the water", "subs": ["power used because it is available", "the rule enforced without care", "authority that permits no successor", "command as appetite"]},
    {"lead": "Delayed", "key": "the office", "subs": ["the authority still being earned", "the office not yet fully held", "rule arriving with experience", "power still consolidating"]}
  ],
  "swords01": [
    {"lead": "Weakened", "key": "the seed", "subs": ["potential that will not germinate", "the gift declined", "a beginning that keeps not starting", "the offer left on the table"]},
    {"lead": "Inverted", "key": "beginning", "subs": ["potential hoarded as identity", "the start endlessly rehearsed", "possibility preferred to actuality", "keeping the gift unopened"]},
    {"lead": "Negative", "key": "the blade", "subs": ["squandering what was given freely", "the seed spent on nothing", "beginning in order never to finish", "wasting a genuine opening"]},
    {"lead": "Delayed", "key": "germination", "subs": ["the seed still under the soil", "germination on its own schedule", "the beginning not yet due", "potential waiting for its season"]}
  ],
  "swords02": [
    {"lead": "Weakened", "key": "the pair", "subs": ["the bond thinning", "exchange that has gone one-way", "relation losing its charge", "two drifting out of contact"]},
    {"lead": "Inverted", "key": "union", "subs": ["union sought to avoid being one", "pairing as a hiding place", "the other used as a mirror", "relation that erases both"]},
    {"lead": "Negative", "key": "the blade", "subs": ["the bond kept for leverage", "dependency dressed as devotion", "tying another to your lack", "partnership as quiet control"]},
    {"lead": "Delayed", "key": "the meeting", "subs": ["the meeting not yet made", "the pair still forming", "connection arriving late", "the second half still on its way"]}
  ],
  "swords03": [
    {"lead": "Weakened", "key": "the issue", "subs": ["growth that stalls early", "the result thinner than hoped", "expression losing its nerve", "the third not quite arriving"]},
    {"lead": "Inverted", "key": "growth", "subs": ["output produced for the look of it", "growth pursued past its use", "expression as performance", "fruit forced before ripening"]},
    {"lead": "Negative", "key": "the blade", "subs": ["creating in order to be admired", "the work exploiting its makers", "growth that consumes its ground", "fertility turned to excess"]},
    {"lead": "Delayed", "key": "the result", "subs": ["the result still forming", "expression finding its shape", "growth on a slow schedule", "the third not yet born"]}
  ],
  "swords04": [
    {"lead": "Weakened", "key": "the square", "subs": ["the structure loosening", "stability with a crack in it", "the enclosure less firm than it looks", "order beginning to slip"]},
    {"lead": "Inverted", "key": "stability", "subs": ["walls kept after the need has passed", "stability defended as an identity", "the pause become permanent", "structure serving only itself"]},
    {"lead": "Negative", "key": "the blade", "subs": ["the enclosure used to shut others out", "security bought with rigidity", "hoarding disguised as prudence", "order enforced without reason"]},
    {"lead": "Delayed", "key": "consolidation", "subs": ["the structure still being built", "stability not yet reached", "the square not yet closed", "consolidation still under way"]}
  ],
  "swords05": [
    {"lead": "Weakened", "key": "the break", "subs": ["disruption that will not resolve", "the disturbance dragging on", "instability become the norm", "the pivot stuck mid-turn"]},
    {"lead": "Inverted", "key": "disruption", "subs": ["conflict maintained on purpose", "crisis preferred to settlement", "the break made into a home", "disruption as an identity"]},
    {"lead": "Negative", "key": "the blade", "subs": ["breaking things to feel the movement", "the wound kept deliberately open", "crisis manufactured for advantage", "harm passed on down the line"]},
    {"lead": "Delayed", "key": "resolution", "subs": ["the disruption still working through", "the break not yet healed", "movement that has further to go", "resolution some way off"]}
  ],
  "swords06": [
    {"lead": "Weakened", "key": "the balance", "subs": ["harmony that will not quite hold", "exchange slightly off true", "the middle wobbling", "proportion drifting"]},
    {"lead": "Inverted", "key": "harmony", "subs": ["balance kept by suppressing one side", "harmony that forbids disagreement", "the peace of not speaking", "evenness enforced, not found"]},
    {"lead": "Negative", "key": "the blade", "subs": ["fairness used to avoid generosity", "the exchange rigged and called even", "harmony demanded of others only", "balance as a way to withhold"]},
    {"lead": "Delayed", "key": "the exchange", "subs": ["the balance still being found", "the exchange not yet even", "harmony arriving gradually", "the middle still being located"]}
  ],
  "swords07": [
    {"lead": "Weakened", "key": "the trial", "subs": ["effort losing its edge", "resistance wearing you down", "the test dragging past its point", "strain without progress"]},
    {"lead": "Inverted", "key": "the struggle", "subs": ["difficulty sought to prove something", "the trial extended on purpose", "struggle as a badge", "hardship mistaken for merit"]},
    {"lead": "Negative", "key": "the blade", "subs": ["making it hard for everyone else", "the fight picked for its own sake", "effort that damages the effort", "grinding past all usefulness"]},
    {"lead": "Delayed", "key": "the outcome", "subs": ["the trial not yet finished", "the test still being sat", "resolution the far side of effort", "the strain still to be borne"]}
  ],
  "swords08": [
    {"lead": "Weakened", "key": "the order", "subs": ["the arrangement slipping", "structure under more load than it takes", "pattern beginning to fray", "organisation losing its grip"]},
    {"lead": "Inverted", "key": "structure", "subs": ["order kept past its usefulness", "structure that has forgotten its purpose", "arrangement as a form of control", "the system serving itself"]},
    {"lead": "Negative", "key": "the blade", "subs": ["order imposed regardless of cost", "efficiency above every other thing", "the pattern enforced on people", "structure used to exclude"]},
    {"lead": "Delayed", "key": "the pattern", "subs": ["the order still being assembled", "structure not yet holding", "arrangement still being tested", "the pattern still emerging"]}
  ],
  "swords09": [
    {"lead": "Weakened", "key": "the fullness", "subs": ["the height not quite reached", "sufficiency that does not satisfy", "fullness with something missing", "the summit thinning out"]},
    {"lead": "Inverted", "key": "sufficiency", "subs": ["completeness defended in solitude", "self-sufficiency as a wall", "fullness that refuses company", "having, and hiding it"]},
    {"lead": "Negative", "key": "the blade", "subs": ["abundance used to keep others out", "solitude at the top made a virtue", "hoarding the view", "sufficiency that excludes"]},
    {"lead": "Delayed", "key": "the summit", "subs": ["the fullness still filling", "the height still being climbed", "sufficiency near but not here", "the last stretch remaining"]}
  ],
  "swords10": [
    {"lead": "Weakened", "key": "the overflow", "subs": ["completion tipping into too much", "the container failing", "surplus becoming burden", "the end that will not end"]},
    {"lead": "Inverted", "key": "completion", "subs": ["completion refused so it can continue", "the surplus kept from circulating", "ending avoided by adding more", "excess mistaken for success"]},
    {"lead": "Negative", "key": "the blade", "subs": ["overflow dumped onto other people", "hoarding at the point of plenty", "the weight passed down the line", "surplus that crushes its holder"]},
    {"lead": "Delayed", "key": "the return", "subs": ["the cycle still closing", "the return to one still coming", "completion on its final approach", "the overflow not yet released"]}
  ],
  "swords11": [
    {"lead": "Weakened", "key": "the apprentice", "subs": ["eagerness without follow-through", "study that will not settle", "the message half-delivered", "keenness thinning quickly"]},
    {"lead": "Inverted", "key": "learning", "subs": ["beginning endlessly to avoid mastering", "the student role kept too long", "curiosity as a way of not committing", "learning performed, not done"]},
    {"lead": "Negative", "key": "the blade", "subs": ["the messenger who distorts the message", "immaturity used as an excuse", "talent squandered on distraction", "promise traded on indefinitely"]},
    {"lead": "Delayed", "key": "readiness", "subs": ["the apprenticeship still running", "skill still being gathered", "the message still on its way", "readiness not yet arrived"]}
  ],
  "swords12": [
    {"lead": "Weakened", "key": "the quest", "subs": ["momentum draining", "the ride losing its direction", "commitment that will not hold pace", "the journey stalling"]},
    {"lead": "Inverted", "key": "the ride", "subs": ["movement chosen to avoid arriving", "the quest as a way of leaving", "speed mistaken for progress", "riding past what you wanted"]},
    {"lead": "Negative", "key": "the blade", "subs": ["charging over other people", "recklessness with someone else's ground", "the journey that ruins what it crosses", "haste made into a virtue"]},
    {"lead": "Delayed", "key": "arrival", "subs": ["the ride still under way", "arrival further off than it looked", "the quest mid-course", "the destination still ahead"]}
  ],
  "swords13": [
    {"lead": "Weakened", "key": "the inward hold", "subs": ["mastery that is costing effort", "depth harder to reach than usual", "the inner grip loosening", "composure thinning"]},
    {"lead": "Inverted", "key": "depth", "subs": ["interiority used to stay unreachable", "depth as a way of withholding", "understanding kept private on principle", "the vessel that never pours"]},
    {"lead": "Negative", "key": "the blade", "subs": ["reading others in order to manage them", "empathy turned to advantage", "inwardness that swallows other people", "depth used to dominate quietly"]},
    {"lead": "Delayed", "key": "mastery", "subs": ["the mastery still forming", "depth still being earned", "the inward work unfinished", "understanding still gathering"]}
  ],
  "swords14": [
    {"lead": "Weakened", "key": "the rule", "subs": ["authority losing its weight", "command that no longer carries", "the office held loosely", "power thinning at the edges"]},
    {"lead": "Inverted", "key": "authority", "subs": ["rule maintained for its own sake", "authority that has stopped serving", "the office mistaken for the person", "governing to remain governor"]},
    {"lead": "Negative", "key": "the blade", "subs": ["power used because it is available", "the rule enforced without care", "authority that permits no successor", "command as appetite"]},
    {"lead": "Delayed", "key": "the office", "subs": ["the authority still being earned", "the office not yet fully held", "rule arriving with experience", "power still consolidating"]}
  ],
  "pents01": [
    {"lead": "Weakened", "key": "the seed", "subs": ["potential that will not germinate", "the gift declined", "a beginning that keeps not starting", "the offer left on the table"]},
    {"lead": "Inverted", "key": "beginning", "subs": ["potential hoarded as identity", "the start endlessly rehearsed", "possibility preferred to actuality", "keeping the gift unopened"]},
    {"lead": "Negative", "key": "the ground", "subs": ["squandering what was given freely", "the seed spent on nothing", "beginning in order never to finish", "wasting a genuine opening"]},
    {"lead": "Delayed", "key": "germination", "subs": ["the seed still under the soil", "germination on its own schedule", "the beginning not yet due", "potential waiting for its season"]}
  ],
  "pents02": [
    {"lead": "Weakened", "key": "the pair", "subs": ["the bond thinning", "exchange that has gone one-way", "relation losing its charge", "two drifting out of contact"]},
    {"lead": "Inverted", "key": "union", "subs": ["union sought to avoid being one", "pairing as a hiding place", "the other used as a mirror", "relation that erases both"]},
    {"lead": "Negative", "key": "the ground", "subs": ["the bond kept for leverage", "dependency dressed as devotion", "tying another to your lack", "partnership as quiet control"]},
    {"lead": "Delayed", "key": "the meeting", "subs": ["the meeting not yet made", "the pair still forming", "connection arriving late", "the second half still on its way"]}
  ],
  "pents03": [
    {"lead": "Weakened", "key": "the issue", "subs": ["growth that stalls early", "the result thinner than hoped", "expression losing its nerve", "the third not quite arriving"]},
    {"lead": "Inverted", "key": "growth", "subs": ["output produced for the look of it", "growth pursued past its use", "expression as performance", "fruit forced before ripening"]},
    {"lead": "Negative", "key": "the ground", "subs": ["creating in order to be admired", "the work exploiting its makers", "growth that consumes its ground", "fertility turned to excess"]},
    {"lead": "Delayed", "key": "the result", "subs": ["the result still forming", "expression finding its shape", "growth on a slow schedule", "the third not yet born"]}
  ],
  "pents04": [
    {"lead": "Weakened", "key": "the square", "subs": ["the structure loosening", "stability with a crack in it", "the enclosure less firm than it looks", "order beginning to slip"]},
    {"lead": "Inverted", "key": "stability", "subs": ["walls kept after the need has passed", "stability defended as an identity", "the pause become permanent", "structure serving only itself"]},
    {"lead": "Negative", "key": "the ground", "subs": ["the enclosure used to shut others out", "security bought with rigidity", "hoarding disguised as prudence", "order enforced without reason"]},
    {"lead": "Delayed", "key": "consolidation", "subs": ["the structure still being built", "stability not yet reached", "the square not yet closed", "consolidation still under way"]}
  ],
  "pents05": [
    {"lead": "Weakened", "key": "the break", "subs": ["disruption that will not resolve", "the disturbance dragging on", "instability become the norm", "the pivot stuck mid-turn"]},
    {"lead": "Inverted", "key": "disruption", "subs": ["conflict maintained on purpose", "crisis preferred to settlement", "the break made into a home", "disruption as an identity"]},
    {"lead": "Negative", "key": "the ground", "subs": ["breaking things to feel the movement", "the wound kept deliberately open", "crisis manufactured for advantage", "harm passed on down the line"]},
    {"lead": "Delayed", "key": "resolution", "subs": ["the disruption still working through", "the break not yet healed", "movement that has further to go", "resolution some way off"]}
  ],
  "pents06": [
    {"lead": "Weakened", "key": "the balance", "subs": ["harmony that will not quite hold", "exchange slightly off true", "the middle wobbling", "proportion drifting"]},
    {"lead": "Inverted", "key": "harmony", "subs": ["balance kept by suppressing one side", "harmony that forbids disagreement", "the peace of not speaking", "evenness enforced, not found"]},
    {"lead": "Negative", "key": "the ground", "subs": ["fairness used to avoid generosity", "the exchange rigged and called even", "harmony demanded of others only", "balance as a way to withhold"]},
    {"lead": "Delayed", "key": "the exchange", "subs": ["the balance still being found", "the exchange not yet even", "harmony arriving gradually", "the middle still being located"]}
  ],
  "pents07": [
    {"lead": "Weakened", "key": "the trial", "subs": ["effort losing its edge", "resistance wearing you down", "the test dragging past its point", "strain without progress"]},
    {"lead": "Inverted", "key": "the struggle", "subs": ["difficulty sought to prove something", "the trial extended on purpose", "struggle as a badge", "hardship mistaken for merit"]},
    {"lead": "Negative", "key": "the ground", "subs": ["making it hard for everyone else", "the fight picked for its own sake", "effort that damages the effort", "grinding past all usefulness"]},
    {"lead": "Delayed", "key": "the outcome", "subs": ["the trial not yet finished", "the test still being sat", "resolution the far side of effort", "the strain still to be borne"]}
  ],
  "pents08": [
    {"lead": "Weakened", "key": "the order", "subs": ["the arrangement slipping", "structure under more load than it takes", "pattern beginning to fray", "organisation losing its grip"]},
    {"lead": "Inverted", "key": "structure", "subs": ["order kept past its usefulness", "structure that has forgotten its purpose", "arrangement as a form of control", "the system serving itself"]},
    {"lead": "Negative", "key": "the ground", "subs": ["order imposed regardless of cost", "efficiency above every other thing", "the pattern enforced on people", "structure used to exclude"]},
    {"lead": "Delayed", "key": "the pattern", "subs": ["the order still being assembled", "structure not yet holding", "arrangement still being tested", "the pattern still emerging"]}
  ],
  "pents09": [
    {"lead": "Weakened", "key": "the fullness", "subs": ["the height not quite reached", "sufficiency that does not satisfy", "fullness with something missing", "the summit thinning out"]},
    {"lead": "Inverted", "key": "sufficiency", "subs": ["completeness defended in solitude", "self-sufficiency as a wall", "fullness that refuses company", "having, and hiding it"]},
    {"lead": "Negative", "key": "the ground", "subs": ["abundance used to keep others out", "solitude at the top made a virtue", "hoarding the view", "sufficiency that excludes"]},
    {"lead": "Delayed", "key": "the summit", "subs": ["the fullness still filling", "the height still being climbed", "sufficiency near but not here", "the last stretch remaining"]}
  ],
  "pents10": [
    {"lead": "Weakened", "key": "the overflow", "subs": ["completion tipping into too much", "the container failing", "surplus becoming burden", "the end that will not end"]},
    {"lead": "Inverted", "key": "completion", "subs": ["completion refused so it can continue", "the surplus kept from circulating", "ending avoided by adding more", "excess mistaken for success"]},
    {"lead": "Negative", "key": "the ground", "subs": ["overflow dumped onto other people", "hoarding at the point of plenty", "the weight passed down the line", "surplus that crushes its holder"]},
    {"lead": "Delayed", "key": "the return", "subs": ["the cycle still closing", "the return to one still coming", "completion on its final approach", "the overflow not yet released"]}
  ],
  "pents11": [
    {"lead": "Weakened", "key": "the apprentice", "subs": ["eagerness without follow-through", "study that will not settle", "the message half-delivered", "keenness thinning quickly"]},
    {"lead": "Inverted", "key": "learning", "subs": ["beginning endlessly to avoid mastering", "the student role kept too long", "curiosity as a way of not committing", "learning performed, not done"]},
    {"lead": "Negative", "key": "the ground", "subs": ["the messenger who distorts the message", "immaturity used as an excuse", "talent squandered on distraction", "promise traded on indefinitely"]},
    {"lead": "Delayed", "key": "readiness", "subs": ["the apprenticeship still running", "skill still being gathered", "the message still on its way", "readiness not yet arrived"]}
  ],
  "pents12": [
    {"lead": "Weakened", "key": "the quest", "subs": ["momentum draining", "the ride losing its direction", "commitment that will not hold pace", "the journey stalling"]},
    {"lead": "Inverted", "key": "the ride", "subs": ["movement chosen to avoid arriving", "the quest as a way of leaving", "speed mistaken for progress", "riding past what you wanted"]},
    {"lead": "Negative", "key": "the ground", "subs": ["charging over other people", "recklessness with someone else's ground", "the journey that ruins what it crosses", "haste made into a virtue"]},
    {"lead": "Delayed", "key": "arrival", "subs": ["the ride still under way", "arrival further off than it looked", "the quest mid-course", "the destination still ahead"]}
  ],
  "pents13": [
    {"lead": "Weakened", "key": "the inward hold", "subs": ["mastery that is costing effort", "depth harder to reach than usual", "the inner grip loosening", "composure thinning"]},
    {"lead": "Inverted", "key": "depth", "subs": ["interiority used to stay unreachable", "depth as a way of withholding", "understanding kept private on principle", "the vessel that never pours"]},
    {"lead": "Negative", "key": "the ground", "subs": ["reading others in order to manage them", "empathy turned to advantage", "inwardness that swallows other people", "depth used to dominate quietly"]},
    {"lead": "Delayed", "key": "mastery", "subs": ["the mastery still forming", "depth still being earned", "the inward work unfinished", "understanding still gathering"]}
  ],
  "pents14": [
    {"lead": "Weakened", "key": "the rule", "subs": ["authority losing its weight", "command that no longer carries", "the office held loosely", "power thinning at the edges"]},
    {"lead": "Inverted", "key": "authority", "subs": ["rule maintained for its own sake", "authority that has stopped serving", "the office mistaken for the person", "governing to remain governor"]},
    {"lead": "Negative", "key": "the ground", "subs": ["power used because it is available", "the rule enforced without care", "authority that permits no successor", "command as appetite"]},
    {"lead": "Delayed", "key": "the office", "subs": ["the authority still being earned", "the office not yet fully held", "rule arriving with experience", "power still consolidating"]}
  ]
};
