// Tarot de Marseille meanings (upright). Read in the Marseille
// tradition: the trumps plainly and medievally, and the pips by
// NUMBER meeting SUIT — because Marseille pips are non-scenic,
// so there is no pictured scene to describe. Note VIII is Justice
// and XI is Force here, the reverse of the Rider-Waite.
// Generated by marseille/_gen_meanings.py — edit the content
// modules there, not this file.
const CARD_ACTIONS_MARSEILLE = {
  "maj00": [
    {"lead": "walking", "key": "unnumbered", "subs": ["outside the sequence entirely", "the only trump without a number", "free because nothing counts him", "belonging to no place, so to all"]},
    {"lead": "carrying", "key": "everything he owns", "subs": ["a bundle on a stick, nothing more", "travelling light by necessity", "the world reduced to what you hold", "poverty that reads as freedom"]},
    {"lead": "moving", "key": "on", "subs": ["the dog at his heel, urging him", "leaving before the story finishes", "the road as the only home", "wandering with intent, not lost"]}
  ],
  "maj01": [
    {"lead": "laying out", "key": "the table", "subs": ["cups, coins, blade, all to hand", "the four suits as working tools", "everything needed, nothing yet made", "beginning with what is in front of you"]},
    {"lead": "holding", "key": "the wand", "subs": ["one hand up, one hand down", "channel between above and below", "skill that has not chosen its use", "the gesture that starts the work"]},
    {"lead": "practising", "key": "the craft", "subs": ["the juggler, the trickster, the maker", "sleight of hand or true art", "talent still deciding what it is", "opening the shop for the day"]}
  ],
  "maj02": [
    {"lead": "pointing", "key": "skyward", "subs": ["one finger raised to the clouds", "attention drawn above the visible", "the queen of heaven at her station", "what she knows, she indicates"]},
    {"lead": "keeping", "key": "her own counsel", "subs": ["sovereign without a throne", "majesty carried, not seated", "guardian of thresholds and vows", "dignity that needs no book"]},
    {"lead": "walking", "key": "with peacocks", "subs": ["the hundred-eyed watch at her feet", "beauty that is also vigilance", "seen more than she is seeing", "splendour as a way of knowing"]}
  ],
  "maj03": [
    {"lead": "holding", "key": "the shield", "subs": ["the eagle resting on her arm", "authority that shelters rather than rules", "power turned toward tending", "protection offered, not imposed"]},
    {"lead": "bringing", "key": "into form", "subs": ["thought made into something living", "the fertile turn of an idea", "what was imagined now growing", "creation as ordinary labour"]},
    {"lead": "presiding", "key": "over increase", "subs": ["abundance that arrives quietly", "the sceptre held lightly", "governing by nourishing", "worldly things flourishing"]}
  ],
  "maj04": [
    {"lead": "sitting", "key": "in profile", "subs": ["legs crossed in the figure four", "settled, weighty, hard to move", "the body itself as a structure", "stability you can lean against"]},
    {"lead": "holding", "key": "the ground", "subs": ["what is established stays established", "order maintained by presence alone", "the rule that needs no argument", "solidity as the whole argument"]},
    {"lead": "ruling", "key": "the visible world", "subs": ["matter, borders, law, the built", "authority that answers to no mood", "the father as fact, not feeling", "power that has stopped moving"]}
  ],
  "maj05": [
    {"lead": "holding", "key": "the thunderbolt", "subs": ["power in either hand", "authority that needs no chair", "command carried openly", "the sky's weight, hand-held"]},
    {"lead": "riding", "key": "the eagle", "subs": ["borne up by what he rules", "standing on wings in the clouds", "sovereignty above the weather", "the height that sees whole"]},
    {"lead": "granting", "key": "and withholding", "subs": ["the father who says yes and no", "law spoken from the sky", "favour that must be asked", "judgement above appeal"]}
  ],
  "maj06": [
    {"lead": "standing", "key": "at the crossing", "subs": ["three figures and an archer above", "the choice made under a loosed arrow", "not romance so much as decision", "one path taken, the rest closed"]},
    {"lead": "being", "key": "pulled two ways", "subs": ["the familiar against the new", "two claims, both legitimate", "affection as a form of gravity", "the difficulty of wanting both"]},
    {"lead": "choosing", "key": "with the whole self", "subs": ["a decision the body makes too", "commitment that costs something", "love as an act of election", "the moment the fork is passed"]}
  ],
  "maj07": [
    {"lead": "standing", "key": "in the car", "subs": ["upright, crowned, already moving", "carried rather than walking", "a young power going forward", "the vehicle built to be seen"]},
    {"lead": "driving", "key": "two horses", "subs": ["one facing out, one facing across", "held together by will alone", "no reins visible on the card", "steering by intent, not equipment"]},
    {"lead": "arriving", "key": "somewhere", "subs": ["the campaign that has begun", "momentum that must be aimed", "conquest, or simply travel", "victory before it has been tested"]}
  ],
  "maj08": [
    {"lead": "holding", "key": "the scales", "subs": ["the eighth trump in this deck", "measure applied without apology", "weighing that does not hurry", "the balance held level and still"]},
    {"lead": "raising", "key": "the sword", "subs": ["blade upright, edge unturned", "discernment that cuts cleanly", "the decision that follows the weighing", "justice as an act, not an idea"]},
    {"lead": "facing", "key": "straight ahead", "subs": ["the only fully frontal figure", "meeting the matter without evasion", "no profile, no angle, no dodge", "seeing exactly what is the case"]}
  ],
  "maj09": [
    {"lead": "carrying", "key": "the lantern", "subs": ["a small light held out at arm's length", "illuminating only the next step", "what he can see, he can share", "the lamp shielded by his cloak"]},
    {"lead": "walking", "key": "slowly", "subs": ["the staff taking his weight", "age as accumulated pace", "going alone because it is quicker", "no destination named on the card"]},
    {"lead": "withdrawing", "key": "to see", "subs": ["solitude chosen, not suffered", "stepping out of the noise", "the long look that needs quiet", "prudence as a way of living"]}
  ],
  "maj10": [
    {"lead": "turning", "key": "without a handle", "subs": ["no one is cranking this wheel", "motion with no visible cause", "the turn that happens to you", "chance running on its own"]},
    {"lead": "riding", "key": "up or down", "subs": ["creatures rising and falling together", "the one climbing, the one descending", "position as a temporary condition", "whoever is up is on their way down"]},
    {"lead": "watching", "key": "fortune move", "subs": ["cycles indifferent to merit", "the sphinx crowned on top, for now", "timing that owes you nothing", "what turns will turn again"]}
  ],
  "maj11": [
    {"lead": "opening", "key": "the lion's mouth", "subs": ["the eleventh trump in this deck", "hands calm on the jaws", "no strain visible anywhere", "the beast neither killed nor fled"]},
    {"lead": "applying", "key": "quiet force", "subs": ["strength that does not look like effort", "mastery without domination", "the wide hat, the untroubled face", "power exercised gently"]},
    {"lead": "holding", "key": "the animal", "subs": ["instinct handled, not suppressed", "the wild kept close and known", "courage that stays soft", "living alongside your own appetite"]}
  ],
  "maj12": [
    {"lead": "hanging", "key": "by one foot", "subs": ["suspended from a living frame", "the free leg crossed behind", "upside down and untroubled", "held rather than falling"]},
    {"lead": "waiting", "key": "inverted", "subs": ["the world seen the other way up", "a pause that cannot be hurried", "stillness imposed from outside", "hands hidden behind his back"]},
    {"lead": "giving", "key": "something up", "subs": ["the coins spilling from his pockets", "surrender that buys a new view", "sacrifice with no audience", "letting the reversal teach"]}
  ],
  "maj13": [
    {"lead": "holding", "key": "the scythe", "subs": ["the trump with no name printed", "the blade already in motion", "what is cut is cut without malice", "the nameless arcanum, XIII"]},
    {"lead": "clearing", "key": "the field", "subs": ["hands and heads still in the soil", "the ground made ready by stripping", "harvest and end as one act", "removal that precedes growth"]},
    {"lead": "ending", "key": "without ceremony", "subs": ["transformation that does not ask", "the door closing on its own", "impersonal, thorough, complete", "an ending that will not be argued"]}
  ],
  "maj14": [
    {"lead": "pouring", "key": "between vessels", "subs": ["liquid passing from urn to urn", "nothing spilled, nothing lost", "the flow continuous in both directions", "an exchange with no container empty"]},
    {"lead": "standing", "key": "winged", "subs": ["an angel, but plainly at work", "the miraculous doing something ordinary", "poise held while pouring", "grace as a practical activity"]},
    {"lead": "tempering", "key": "the mixture", "subs": ["two things becoming one thing", "the right proportion found slowly", "moderation as active craft", "healing by combination"]}
  ],
  "maj15": [
    {"lead": "standing", "key": "on the pedestal", "subs": ["raised above two small figures", "the horned one, torch in hand", "power that requires an audience", "elevation as the whole trick"]},
    {"lead": "holding", "key": "the tethers", "subs": ["loose ropes around willing necks", "bonds that could be slipped", "the captivity you cooperate with", "chains kept comfortable on purpose"]},
    {"lead": "wanting", "key": "badly", "subs": ["appetite that has taken the throne", "what you cannot put down", "the material grip, fully felt", "compulsion mistaken for choice"]}
  ],
  "maj16": [
    {"lead": "splitting", "key": "the crown", "subs": ["the tower's top blown clean off", "lightning arriving without warning", "the structure opened at its head", "what was highest goes first"]},
    {"lead": "falling", "key": "out", "subs": ["two figures thrown into the air", "coloured drops scattered all round", "no ground shown to land on", "descent still in progress"]},
    {"lead": "losing", "key": "the shelter", "subs": ["the built thing proved provisional", "sudden clearance of a false safety", "release that arrives as damage", "correction from outside the plan"]}
  ],
  "maj17": [
    {"lead": "kneeling", "key": "at the water", "subs": ["one knee down, one foot in the stream", "naked without embarrassment", "attending to the source directly", "the posture of pouring, not asking"]},
    {"lead": "emptying", "key": "two jugs", "subs": ["one onto the earth, one into the river", "giving back without measuring", "replenishment that costs nothing", "flow restored to where it came from"]},
    {"lead": "standing", "key": "under stars", "subs": ["one great star and seven around it", "guidance that is simply there", "hope as an ambient condition", "the bird watching from the tree"]}
  ],
  "maj18": [
    {"lead": "shining", "key": "on the ambiguous", "subs": ["light that does not clarify", "the face in the moon looking aside", "drops falling upward toward it", "illumination without definition"]},
    {"lead": "standing", "key": "at the water's edge", "subs": ["two towers, two dogs, one crayfish", "the thing crawling up out of the pool", "the threshold between kinds", "what surfaces at night"]},
    {"lead": "going", "key": "by feel", "subs": ["the path that cannot be seen whole", "instinct where sight fails", "dreams, tides, and the unsaid", "trusting what you cannot verify"]}
  ],
  "maj19": [
    {"lead": "shining", "key": "plainly", "subs": ["a face in the disc, looking out", "rays straight and wavy together", "warmth without mystery", "light that explains itself"]},
    {"lead": "standing", "key": "together", "subs": ["two children before a low wall", "one hand on the other's shoulder", "company as the whole point", "being seen and not minding"]},
    {"lead": "receiving", "key": "the day", "subs": ["drops of colour falling like grace", "clarity after the moon's night", "the simple good, uncomplicated", "gladness that needs no reason"]}
  ],
  "maj20": [
    {"lead": "sounding", "key": "the trumpet", "subs": ["the angel leaning from the cloud", "a call that reaches underground", "summons rather than sentence", "the note that cannot be unheard"]},
    {"lead": "rising", "key": "from the tomb", "subs": ["three figures, one just standing up", "the lid pushed off from inside", "return to a life thought finished", "waking as a communal event"]},
    {"lead": "answering", "key": "for it", "subs": ["the account finally rendered", "what was buried brought into day", "reckoning that also restores", "being called by your own name"]}
  ],
  "maj21": [
    {"lead": "dancing", "key": "in the wreath", "subs": ["a figure held inside an oval", "the garland closed all the way round", "movement inside completion", "framed rather than confined"]},
    {"lead": "gathering", "key": "the four", "subs": ["angel, eagle, lion, bull at the corners", "the whole compass accounted for", "everything present at once", "the four fixed and the one moving"]},
    {"lead": "completing", "key": "the round", "subs": ["the last trump, the closed circle", "arrival that includes the journey", "the world entered, not conquered", "wholeness that keeps dancing"]}
  ],
  "wands01": [
    {"lead": "seeding", "key": "the seed", "subs": ["the whole suit held in one", "potential before it divides", "the gift offered, not yet used", "a beginning with nothing spent"]},
    {"lead": "taking up", "key": "the staff", "subs": ["raw force offered to the hand", "the will before it has a task", "fire at its first ignition", "energy with nowhere yet to go"]},
    {"lead": "beginning", "key": "the work", "subs": ["the project that wants doing", "impulse worth acting on", "a start with real heat in it"]}
  ],
  "wands02": [
    {"lead": "pairing", "key": "the pair", "subs": ["one becoming two", "relation, and therefore tension", "the first exchange", "what needs another to exist"]},
    {"lead": "crossing", "key": "the batons", "subs": ["two forces meeting at an angle", "will against will, productively", "the tension that makes a frame"]},
    {"lead": "holding", "key": "a partnership", "subs": ["shared work, divided labour", "the argument that sharpens both", "an alliance under some strain"]}
  ],
  "wands03": [
    {"lead": "issuing", "key": "the issue", "subs": ["two producing a third", "the first result of a relation", "growth that shows itself", "expression breaking out"]},
    {"lead": "branching", "key": "outward", "subs": ["three staves opening a space", "effort producing its first result", "the work throwing out shoots"]},
    {"lead": "extending", "key": "the reach", "subs": ["ambition finding room to grow", "enterprise widening", "what began small taking ground"]}
  ],
  "wands04": [
    {"lead": "enclosing", "key": "the square", "subs": ["four corners, one enclosure", "the pause that holds its shape", "stability, and its walls", "consolidation before the next move"]},
    {"lead": "framing", "key": "the enclosure", "subs": ["four staves making a stable square", "the work given a structure", "effort with walls around it"]},
    {"lead": "resting", "key": "in the built", "subs": ["a pause that has been earned", "the workshop finally in order", "stability before the next push"]}
  ],
  "wands05": [
    {"lead": "pivoting", "key": "the break", "subs": ["the still point disturbed", "four disrupted by a fifth", "the pivot at the deck's centre", "movement forced on stillness"]},
    {"lead": "clashing", "key": "the staves", "subs": ["batons crossed without agreement", "competing energies in one room", "friction with no clear winner"]},
    {"lead": "contending", "key": "openly", "subs": ["rivalry that is at least honest", "struggle that sharpens the work", "conflict as a sign of life"]}
  ],
  "wands06": [
    {"lead": "settling", "key": "the balance", "subs": ["two threes, evenly met", "harmony after the disruption", "exchange that works", "the settled middle"]},
    {"lead": "aligning", "key": "the forces", "subs": ["staves finding a common angle", "effort and reward in proportion", "the team pulling together"]},
    {"lead": "carrying", "key": "the day", "subs": ["work that is going well", "momentum that others notice", "recognition that fits the effort"]}
  ],
  "wands07": [
    {"lead": "testing", "key": "the trial", "subs": ["balance tested by one more", "the uneven number that strains", "effort against resistance", "what must be won, not given"]},
    {"lead": "holding", "key": "the ground", "subs": ["six against one, and one holds", "defending what you built", "effort under sustained pressure"]},
    {"lead": "persisting", "key": "anyway", "subs": ["the will tested and still standing", "stamina as the deciding factor", "refusing to be pushed off"]}
  ],
  "wands08": [
    {"lead": "arranging", "key": "the order", "subs": ["structure regained, more complex", "arrangement that holds under load", "the pattern proved workable", "organisation as achievement"]},
    {"lead": "ordering", "key": "the energy", "subs": ["force finally organised", "the work moving fast and straight", "direction found for the heat"]},
    {"lead": "moving", "key": "quickly", "subs": ["events accelerating", "the arrow already loosed", "progress that outruns planning"]}
  ],
  "wands09": [
    {"lead": "brimming", "key": "the fullness", "subs": ["the last single figure", "the suit at its greatest extent", "solitude at the top", "as far as this can go alone"]},
    {"lead": "guarding", "key": "alone", "subs": ["the last stave held by one hand", "strength that has been spent and stayed", "vigilance after the battle"]},
    {"lead": "bearing", "key": "the cost", "subs": ["scarred but still standing", "reserves nearly gone, still holding", "the tiredness of nearly finishing"]}
  ],
  "wands10": [
    {"lead": "exceeding", "key": "the overflow", "subs": ["completion tipping into surplus", "the suit exceeding its container", "an end that is also a return", "ten becoming one again"]},
    {"lead": "shouldering", "key": "the bundle", "subs": ["more staves than two arms want", "the work grown past its owner", "success measured in weight"]},
    {"lead": "carrying", "key": "too much", "subs": ["burden taken on willingly", "the load that blocks the view", "finishing under strain"]}
  ],
  "wands11": [
    {"lead": "learning", "key": "the fire", "subs": ["apprenticed to your own energy", "enthusiasm without technique yet", "the messenger carrying good news"]},
    {"lead": "starting", "key": "eagerly", "subs": ["willing before being able", "the first job taken seriously", "keenness that will need shaping"]},
    {"lead": "bringing", "key": "word", "subs": ["news that starts something", "the spark handed to someone else", "an opening announced"]}
  ],
  "wands12": [
    {"lead": "riding", "key": "out", "subs": ["the quest taken up at speed", "energy given a direction", "movement as the whole answer"]},
    {"lead": "charging", "key": "forward", "subs": ["commitment made at a gallop", "boldness ahead of planning", "the departure that will not wait"]},
    {"lead": "pressing", "key": "on", "subs": ["momentum that carries others", "haste that mostly works", "adventure entered willingly"]}
  ],
  "wands13": [
    {"lead": "holding", "key": "the flame inward", "subs": ["fire mastered by being felt", "warmth that draws people in", "authority held without display"]},
    {"lead": "knowing", "key": "your own heat", "subs": ["desire understood, not obeyed", "confidence rooted in self-knowledge", "magnetism that is simply presence"]},
    {"lead": "sustaining", "key": "others", "subs": ["the fire that lights other fires", "encouragement given generously", "warmth as a form of rule"]}
  ],
  "wands14": [
    {"lead": "ruling", "key": "by will", "subs": ["fire turned into command", "vision that others follow", "authority with heat behind it"]},
    {"lead": "directing", "key": "the work", "subs": ["the enterprise led from the front", "decisions made and owned", "leadership as applied energy"]},
    {"lead": "burning", "key": "steadily", "subs": ["force that has learned its pace", "power that no longer proves itself", "the fire kept usefully banked"]}
  ],
  "cups01": [
    {"lead": "seeding", "key": "the seed", "subs": ["the whole suit held in one", "potential before it divides", "the gift offered, not yet used", "a beginning with nothing spent"]},
    {"lead": "receiving", "key": "the vessel", "subs": ["the cup offered, not taken", "feeling before it has an object", "the source, still undivided"]},
    {"lead": "opening", "key": "to it", "subs": ["the heart made available", "affection at its first stirring", "willingness to be moved"]}
  ],
  "cups02": [
    {"lead": "pairing", "key": "the pair", "subs": ["one becoming two", "relation, and therefore tension", "the first exchange", "what needs another to exist"]},
    {"lead": "meeting", "key": "across", "subs": ["two cups facing each other", "the exchange that makes a bond", "feeling that requires a second"]},
    {"lead": "joining", "key": "freely", "subs": ["attraction acknowledged", "the pledge between two people", "affinity finding its match"]}
  ],
  "cups03": [
    {"lead": "issuing", "key": "the issue", "subs": ["two producing a third", "the first result of a relation", "growth that shows itself", "expression breaking out"]},
    {"lead": "spilling", "key": "over", "subs": ["three cups, more than enough", "feeling that becomes company", "joy that has to be shared"]},
    {"lead": "celebrating", "key": "together", "subs": ["the gathering, the toast", "gladness with witnesses", "friendship at its easiest"]}
  ],
  "cups04": [
    {"lead": "enclosing", "key": "the square", "subs": ["four corners, one enclosure", "the pause that holds its shape", "stability, and its walls", "consolidation before the next move"]},
    {"lead": "holding", "key": "steady", "subs": ["four cups, evenly placed", "feeling settled into a shape", "emotion at rest, or at a stop"]},
    {"lead": "sitting", "key": "with enough", "subs": ["contentment, or its cousin boredom", "the heart no longer reaching", "satisfaction that has stopped moving"]}
  ],
  "cups05": [
    {"lead": "pivoting", "key": "the break", "subs": ["the still point disturbed", "four disrupted by a fifth", "the pivot at the deck's centre", "movement forced on stillness"]},
    {"lead": "disturbing", "key": "the water", "subs": ["the fifth cup breaking the square", "feeling knocked out of its settlement", "loss entering a stable thing"]},
    {"lead": "feeling", "key": "the lack", "subs": ["what is missing, plainly felt", "grief that has not been arranged", "the ache that moves you again"]}
  ],
  "cups06": [
    {"lead": "settling", "key": "the balance", "subs": ["two threes, evenly met", "harmony after the disruption", "exchange that works", "the settled middle"]},
    {"lead": "flowing", "key": "evenly", "subs": ["six cups in easy proportion", "feeling given and returned", "emotional exchange that balances"]},
    {"lead": "remembering", "key": "kindly", "subs": ["the past softened by affection", "sweetness without demand", "tenderness that costs nothing"]}
  ],
  "cups07": [
    {"lead": "testing", "key": "the trial", "subs": ["balance tested by one more", "the uneven number that strains", "effort against resistance", "what must be won, not given"]},
    {"lead": "multiplying", "key": "the wants", "subs": ["seven cups, too many to choose", "desire outrunning judgement", "feeling scattered across options"]},
    {"lead": "wanting", "key": "everything", "subs": ["appetite that will not settle", "imagination mistaken for intention", "the trial of too much choice"]}
  ],
  "cups08": [
    {"lead": "arranging", "key": "the order", "subs": ["structure regained, more complex", "arrangement that holds under load", "the pattern proved workable", "organisation as achievement"]},
    {"lead": "ordering", "key": "the feeling", "subs": ["emotion given a workable shape", "the heart arranged, not denied", "structure that lets feeling last"]},
    {"lead": "moving", "key": "on purpose", "subs": ["leaving what no longer holds water", "choosing depth over quantity", "turning away with reason"]}
  ],
  "cups09": [
    {"lead": "brimming", "key": "the fullness", "subs": ["the last single figure", "the suit at its greatest extent", "solitude at the top", "as far as this can go alone"]},
    {"lead": "filling", "key": "completely", "subs": ["nine cups, the suit at its widest", "satisfaction reached and held", "feeling at its greatest extent"]},
    {"lead": "enjoying", "key": "fully", "subs": ["the wish granted, plainly", "pleasure without apology", "abundance you can actually feel"]}
  ],
  "cups10": [
    {"lead": "exceeding", "key": "the overflow", "subs": ["completion tipping into surplus", "the suit exceeding its container", "an end that is also a return", "ten becoming one again"]},
    {"lead": "overflowing", "key": "the measure", "subs": ["ten cups, more than can be held", "feeling beyond private capacity", "the heart's account in surplus"]},
    {"lead": "belonging", "key": "together", "subs": ["joy that includes other people", "the household, not the self", "completion shared out"]}
  ],
  "cups11": [
    {"lead": "learning", "key": "the water", "subs": ["apprenticed to your own feeling", "tenderness without defences", "the messenger bringing affection"]},
    {"lead": "opening", "key": "first", "subs": ["offering the heart before it is safe", "sincerity ahead of experience", "willingness to be affected"]},
    {"lead": "bringing", "key": "an offer", "subs": ["the invitation extended", "feeling put into words", "a gesture made without cover"]}
  ],
  "cups12": [
    {"lead": "riding", "key": "toward", "subs": ["the quest undertaken for love", "feeling given a destination", "approach made in good faith"]},
    {"lead": "courting", "key": "openly", "subs": ["the proposal carried in person", "romance as a journey outward", "devotion that travels"]},
    {"lead": "following", "key": "the heart", "subs": ["direction chosen by feeling", "the pursuit of what moves you", "commitment on the move"]}
  ],
  "cups13": [
    {"lead": "holding", "key": "the deep", "subs": ["feeling mastered by being felt through", "emotion held without spilling", "the still water that goes down far"]},
    {"lead": "knowing", "key": "the currents", "subs": ["empathy that reads accurately", "understanding without needing told", "intuition as practised skill"]},
    {"lead": "containing", "key": "others", "subs": ["the vessel people can pour into", "compassion with real capacity", "care that does not drown"]}
  ],
  "cups14": [
    {"lead": "ruling", "key": "by feeling", "subs": ["water turned into authority", "governing with the heart involved", "power exercised kindly"]},
    {"lead": "holding", "key": "the cup steady", "subs": ["emotion mastered under pressure", "calm that steadies a room", "maturity in the feeling life"]},
    {"lead": "presiding", "key": "warmly", "subs": ["leadership people trust", "the diplomat's instinct", "authority that stays humane"]}
  ],
  "swords01": [
    {"lead": "seeding", "key": "the seed", "subs": ["the whole suit held in one", "potential before it divides", "the gift offered, not yet used", "a beginning with nothing spent"]},
    {"lead": "drawing", "key": "the blade", "subs": ["one sword, edge upright", "mind before it has an object", "clarity at its first arrival"]},
    {"lead": "seeing", "key": "plainly", "subs": ["the thought that cuts through", "truth arriving without padding", "the decision becoming possible"]}
  ],
  "swords02": [
    {"lead": "pairing", "key": "the pair", "subs": ["one becoming two", "relation, and therefore tension", "the first exchange", "what needs another to exist"]},
    {"lead": "crossing", "key": "the blades", "subs": ["two swords held against each other", "thought divided against itself", "the standoff inside one head"]},
    {"lead": "weighing", "key": "both", "subs": ["two accounts, equally armed", "suspension between two truths", "the choice not yet made"]}
  ],
  "swords03": [
    {"lead": "issuing", "key": "the issue", "subs": ["two producing a third", "the first result of a relation", "growth that shows itself", "expression breaking out"]},
    {"lead": "piercing", "key": "through", "subs": ["a third blade between two", "thought that wounds as it clarifies", "the cut that cannot be unseen"]},
    {"lead": "knowing", "key": "the hurt", "subs": ["understanding that costs something", "grief arriving as a fact", "the truth that hurts and holds"]}
  ],
  "swords04": [
    {"lead": "enclosing", "key": "the square", "subs": ["four corners, one enclosure", "the pause that holds its shape", "stability, and its walls", "consolidation before the next move"]},
    {"lead": "laying", "key": "the blades down", "subs": ["four swords at rest", "the mind stood down", "thought given a quiet room"]},
    {"lead": "resting", "key": "the mind", "subs": ["the pause that prevents error", "withdrawal to think properly", "silence as a working method"]}
  ],
  "swords05": [
    {"lead": "pivoting", "key": "the break", "subs": ["the still point disturbed", "four disrupted by a fifth", "the pivot at the deck's centre", "movement forced on stillness"]},
    {"lead": "breaking", "key": "the order", "subs": ["the fifth blade unsettles four", "argument entering a settled room", "conflict that cannot be tidied"]},
    {"lead": "cutting", "key": "too far", "subs": ["the point won at some cost", "words that went past their purpose", "victory that damages the ground"]}
  ],
  "swords06": [
    {"lead": "settling", "key": "the balance", "subs": ["two threes, evenly met", "harmony after the disruption", "exchange that works", "the settled middle"]},
    {"lead": "balancing", "key": "the blades", "subs": ["six swords in workable order", "thought and feeling in proportion", "the mind steadied again"]},
    {"lead": "crossing", "key": "over", "subs": ["passage to calmer water", "the move that improves the terms", "leaving trouble deliberately"]}
  ],
  "swords07": [
    {"lead": "testing", "key": "the trial", "subs": ["balance tested by one more", "the uneven number that strains", "effort against resistance", "what must be won, not given"]},
    {"lead": "straining", "key": "the pattern", "subs": ["seven blades, one out of true", "cleverness against the odds", "thought working around the rule"]},
    {"lead": "managing", "key": "alone", "subs": ["the plan kept to yourself", "tactics rather than force", "getting through by wits"]}
  ],
  "swords08": [
    {"lead": "arranging", "key": "the order", "subs": ["structure regained, more complex", "arrangement that holds under load", "the pattern proved workable", "organisation as achievement"]},
    {"lead": "ordering", "key": "the thought", "subs": ["eight blades in strict arrangement", "the mind's structure, tight", "logic that admits no gap"]},
    {"lead": "binding", "key": "yourself", "subs": ["restriction largely self-made", "the argument that traps its author", "limits that are mostly mental"]}
  ],
  "swords09": [
    {"lead": "brimming", "key": "the fullness", "subs": ["the last single figure", "the suit at its greatest extent", "solitude at the top", "as far as this can go alone"]},
    {"lead": "reaching", "key": "the limit", "subs": ["nine blades, the mind at full extent", "thought alone with itself at night", "the furthest worry can go"]},
    {"lead": "suffering", "key": "the mind", "subs": ["anxiety at its loudest", "the wound rehearsed in the dark", "fear outrunning any fact"]}
  ],
  "swords10": [
    {"lead": "exceeding", "key": "the overflow", "subs": ["completion tipping into surplus", "the suit exceeding its container", "an end that is also a return", "ten becoming one again"]},
    {"lead": "finishing", "key": "the argument", "subs": ["ten blades and nothing left to cut", "the thought carried to its end", "conclusion that empties the field"]},
    {"lead": "ending", "key": "it", "subs": ["the worst of it now behind", "collapse that at least completes", "the bottom, and therefore the turn"]}
  ],
  "swords11": [
    {"lead": "learning", "key": "the blade", "subs": ["apprenticed to your own mind", "sharpness without judgement yet", "the messenger carrying hard news"]},
    {"lead": "watching", "key": "closely", "subs": ["curiosity that misses nothing", "vigilance ahead of wisdom", "the questions asked too directly"]},
    {"lead": "bringing", "key": "word", "subs": ["the fact delivered plainly", "information that changes things", "truth handed over unsoftened"]}
  ],
  "swords12": [
    {"lead": "riding", "key": "in", "subs": ["the argument entered at speed", "intellect on the attack", "decisiveness that does not pause"]},
    {"lead": "cutting", "key": "through", "subs": ["complications solved by force of mind", "directness as a method", "the charge that clears the ground"]},
    {"lead": "acting", "key": "at once", "subs": ["thought converted straight to action", "haste that is sometimes right", "conviction moving fast"]}
  ],
  "swords13": [
    {"lead": "holding", "key": "the edge inward", "subs": ["mind mastered by being examined", "clarity earned through experience", "perception that has cost something"]},
    {"lead": "seeing", "key": "exactly", "subs": ["the eye that is not fooled", "honesty with herself first", "judgement refined by loss"]},
    {"lead": "speaking", "key": "cleanly", "subs": ["truth said without cruelty", "precision as a kindness", "the word that ends the confusion"]}
  ],
  "swords14": [
    {"lead": "ruling", "key": "by law", "subs": ["mind turned into authority", "principle applied consistently", "power that answers to reason"]},
    {"lead": "deciding", "key": "finally", "subs": ["the judgement that settles it", "clarity brought to bear", "the buck stopping properly"]},
    {"lead": "holding", "key": "the standard", "subs": ["integrity as an office", "fairness maintained under pressure", "law above preference"]}
  ],
  "pents01": [
    {"lead": "seeding", "key": "the seed", "subs": ["the whole suit held in one", "potential before it divides", "the gift offered, not yet used", "a beginning with nothing spent"]},
    {"lead": "holding", "key": "the coin", "subs": ["one denier, whole and heavy", "matter offered to the hand", "substance before it is spent"]},
    {"lead": "receiving", "key": "the means", "subs": ["the resource that makes it possible", "health, money, ground, a start", "something real to build on"]}
  ],
  "pents02": [
    {"lead": "pairing", "key": "the pair", "subs": ["one becoming two", "relation, and therefore tension", "the first exchange", "what needs another to exist"]},
    {"lead": "turning", "key": "the two", "subs": ["two coins kept in motion", "resources juggled, not settled", "the balance that requires attention"]},
    {"lead": "managing", "key": "both", "subs": ["making the ends meet", "flexibility under real constraint", "keeping two things going at once"]}
  ],
  "pents03": [
    {"lead": "issuing", "key": "the issue", "subs": ["two producing a third", "the first result of a relation", "growth that shows itself", "expression breaking out"]},
    {"lead": "setting", "key": "the stone", "subs": ["three coins forming a base", "skill applied to material", "the first solid result"]},
    {"lead": "working", "key": "the craft", "subs": ["competence recognised by others", "the trade being learned properly", "labour that shows in the object"]}
  ],
  "pents04": [
    {"lead": "enclosing", "key": "the square", "subs": ["four corners, one enclosure", "the pause that holds its shape", "stability, and its walls", "consolidation before the next move"]},
    {"lead": "squaring", "key": "the holding", "subs": ["four coins, one at each corner", "possession given a firm shape", "matter locked into place"]},
    {"lead": "keeping", "key": "it", "subs": ["security tightly held", "saving, or hoarding, depending", "the grip that steadies and stiffens"]}
  ],
  "pents05": [
    {"lead": "pivoting", "key": "the break", "subs": ["the still point disturbed", "four disrupted by a fifth", "the pivot at the deck's centre", "movement forced on stillness"]},
    {"lead": "unsettling", "key": "the ground", "subs": ["the fifth coin breaks the square", "material security disturbed", "the floor moving underfoot"]},
    {"lead": "going", "key": "without", "subs": ["want that is plainly physical", "the cold outside the wall", "need that cannot be argued with"]}
  ],
  "pents06": [
    {"lead": "settling", "key": "the balance", "subs": ["two threes, evenly met", "harmony after the disruption", "exchange that works", "the settled middle"]},
    {"lead": "evening", "key": "the shares", "subs": ["six coins in fair proportion", "giving and receiving in balance", "material exchange that works"]},
    {"lead": "sharing", "key": "out", "subs": ["generosity with the accounts open", "help given without a hook", "fairness made practical"]}
  ],
  "pents07": [
    {"lead": "testing", "key": "the trial", "subs": ["balance tested by one more", "the uneven number that strains", "effort against resistance", "what must be won, not given"]},
    {"lead": "waiting", "key": "on growth", "subs": ["seven coins, the count not final", "the crop still in the ground", "patience with something material"]},
    {"lead": "assessing", "key": "the return", "subs": ["was the effort worth the yield", "the long look at slow progress", "judgement held until harvest"]}
  ],
  "pents08": [
    {"lead": "arranging", "key": "the order", "subs": ["structure regained, more complex", "arrangement that holds under load", "the pattern proved workable", "organisation as achievement"]},
    {"lead": "ordering", "key": "the work", "subs": ["eight coins in steady arrangement", "the same task done well repeatedly", "structure that produces reliably"]},
    {"lead": "practising", "key": "daily", "subs": ["craft built by repetition", "the unglamorous middle of mastery", "skill compounding quietly"]}
  ],
  "pents09": [
    {"lead": "brimming", "key": "the fullness", "subs": ["the last single figure", "the suit at its greatest extent", "solitude at the top", "as far as this can go alone"]},
    {"lead": "gathering", "key": "the yield", "subs": ["nine coins, the suit at full extent", "material sufficiency reached", "the garden grown and enjoyed alone"]},
    {"lead": "standing", "key": "secure", "subs": ["independence actually achieved", "comfort earned rather than given", "enough, and knowing it"]}
  ],
  "pents10": [
    {"lead": "exceeding", "key": "the overflow", "subs": ["completion tipping into surplus", "the suit exceeding its container", "an end that is also a return", "ten becoming one again"]},
    {"lead": "completing", "key": "the estate", "subs": ["ten coins, more than one life needs", "wealth passing beyond the owner", "the account that outlives you"]},
    {"lead": "providing", "key": "onward", "subs": ["family, legacy, the long term", "stability built for other people", "what remains after you"]}
  ],
  "pents11": [
    {"lead": "learning", "key": "the ground", "subs": ["apprenticed to something practical", "study with a real object", "the messenger with an opportunity"]},
    {"lead": "beginning", "key": "carefully", "subs": ["the first honest work", "patience unusual in a beginner", "willingness to start small"]},
    {"lead": "bringing", "key": "the offer", "subs": ["the opening that has substance", "news of something solid", "a chance worth examining"]}
  ],
  "pents12": [
    {"lead": "riding", "key": "steadily", "subs": ["the quest undertaken at a walk", "progress that will not be hurried", "reliability as the whole method"]},
    {"lead": "labouring", "key": "on", "subs": ["the long haul accepted", "persistence without drama", "the field ploughed to the end"]},
    {"lead": "carrying", "key": "through", "subs": ["what is started gets finished", "dependability as a virtue", "slow motion that arrives"]}
  ],
  "pents13": [
    {"lead": "holding", "key": "the earth inward", "subs": ["matter mastered by being tended", "practical wisdom worn lightly", "the hand that knows the soil"]},
    {"lead": "keeping", "key": "the household", "subs": ["resources managed without fuss", "comfort made for other people", "abundance quietly maintained"]},
    {"lead": "growing", "key": "things", "subs": ["care that makes things thrive", "fertility in the ordinary sense", "the garden as a way of thinking"]}
  ],
  "pents14": [
    {"lead": "ruling", "key": "by substance", "subs": ["earth turned into authority", "wealth that carries obligation", "power grounded in real things"]},
    {"lead": "providing", "key": "reliably", "subs": ["the estate kept in good order", "security extended to others", "stewardship as leadership"]},
    {"lead": "building", "key": "to last", "subs": ["what is made outlasts the maker", "patience at the scale of decades", "solidity as a legacy"]}
  ]
};
