#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Emit cardActionsMarseille.js and cardActionsMarseilleReversed.js.

Writes ONLY the two Marseille files — the Rider-Waite and Thoth data are
never read or touched.

Structure matches the existing decks exactly, so the info overlay renders
them identically:
  upright   key -> [{lead, key, subs[]}, ...]
  reversed  key -> four stanzas, Weakened / Inverted / Negative / Delayed

Every sub is kept to 42 characters or fewer, which is what keeps the
overlay in its flowing middot mode rather than dropping to block lists.
"""
import json
import os

import _content_majors as M
import _content_minors as N

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.dirname(HERE)          # repo root

SUITS = ["wands", "cups", "swords", "pents"]
MAX_SUB = 42

_problems = []


def sub(text):
    if len(text) > MAX_SUB:
        _problems.append("sub too long (%d): %s" % (len(text), text))
    return text


def stanza(lead, key, subs):
    return {"lead": lead, "key": key, "subs": [sub(s) for s in subs]}


def pip_key(suit, n):
    return "%s%02d" % (suit, n)


def build_upright():
    out = {}
    # Trumps
    for k, stanzas in M.UP.items():
        out[k] = [stanza(l, ky, ss) for (l, ky, ss) in stanzas]
    # Pips: the number's quality, then two stanzas authored for this pip.
    for suit in SUITS:
        for n in range(1, 11):
            num_key, num_subs = N.NUMBER_UP[n]
            body = N.PIP[(suit, n)]
            out[pip_key(suit, n)] = (
                [stanza(N.NUMBER_UP_LEAD[n], num_key, num_subs)]
                + [stanza(l, ky, ss) for (l, ky, ss) in body]
            )
    # Courts
    for suit in SUITS:
        for n in (11, 12, 13, 14):
            out[pip_key(suit, n)] = [stanza(l, ky, ss)
                                     for (l, ky, ss) in N.COURT[(suit, n)]]
    return out


def build_reversed():
    out = {}
    for k, stanzas in M.REV.items():
        out[k] = [stanza(l, ky, ss) for (l, ky, ss) in stanzas]

    def four(table, keys, idx, suit):
        """Compose the four WIND stanzas from a number/rank shadow table.
        Each angle carries its own key, as the trumps do."""
        _, weak, inv, neg, dly = table[idx]
        k_weak, k_inv, k_dly = keys[idx]
        return [
            stanza("Weakened", k_weak, weak),
            stanza("Inverted", k_inv, inv),
            stanza("Negative", N.SUIT_REV_WORD[suit], neg),
            stanza("Delayed", k_dly, dly),
        ]

    for suit in SUITS:
        for n in range(1, 11):
            out[pip_key(suit, n)] = four(N.NUMBER_REV, N.NUMBER_REV_KEYS, n, suit)
        for n in (11, 12, 13, 14):
            out[pip_key(suit, n)] = four(N.RANK_REV, N.RANK_REV_KEYS, n, suit)
    return out


def emit(path, const, header, data, keys):
    lines = [header, "const %s = {" % const]
    for i, k in enumerate(keys):
        rows = ",\n".join(
            "    " + json.dumps(s, ensure_ascii=False) for s in data[k]
        )
        comma = "," if i < len(keys) - 1 else ""
        lines.append('  "%s": [\n%s\n  ]%s' % (k, rows, comma))
    lines.append("};")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def main():
    keys = (["maj%02d" % i for i in range(22)]
            + [pip_key(s, n) for s in SUITS for n in range(1, 15)])

    up = build_upright()
    rev = build_reversed()

    missing_up = [k for k in keys if k not in up]
    missing_rev = [k for k in keys if k not in rev]
    assert not missing_up, "upright missing: %s" % missing_up
    assert not missing_rev, "reversed missing: %s" % missing_rev
    assert len(up) == 78 and len(rev) == 78, (len(up), len(rev))
    for k in keys:
        assert len(rev[k]) == 4, "%s has %d reversed stanzas" % (k, len(rev[k]))
        assert len(up[k]) >= 3, "%s has only %d upright stanzas" % (k, len(up[k]))

    if _problems:
        for p in _problems[:20]:
            print("  !", p)
        raise SystemExit("%d subs exceed %d chars" % (len(_problems), MAX_SUB))

    emit(os.path.join(OUT, "cardActionsMarseille.js"),
         "CARD_ACTIONS_MARSEILLE",
         "// Tarot de Marseille meanings (upright). Read in the Marseille\n"
         "// tradition: the trumps plainly and medievally, and the pips by\n"
         "// NUMBER meeting SUIT — because Marseille pips are non-scenic,\n"
         "// so there is no pictured scene to describe. Note VIII is Justice\n"
         "// and XI is Force here, the reverse of the Rider-Waite.\n"
         "// Generated by marseille/_gen_meanings.py — edit the content\n"
         "// modules there, not this file.",
         up, keys)

    emit(os.path.join(OUT, "cardActionsMarseilleReversed.js"),
         "CARD_ACTIONS_REVERSED_MARSEILLE",
         "// Tarot de Marseille meanings (reversed). Four angles —\n"
         "// Weakened / Inverted / Negative / Delayed. For the minors the\n"
         "// number (or court rank) supplies the shape of the failure and\n"
         "// the suit supplies what is failing.\n"
         "// Generated by marseille/_gen_meanings.py — edit the content\n"
         "// modules there, not this file.",
         rev, keys)

    print("wrote both files: 78 upright, 78 reversed, all subs <= %d chars" % MAX_SUB)


if __name__ == "__main__":
    main()
